In [42]:
import requests
from bs4 import BeautifulSoup
#from html_table_parser import parser_functions as parser

def get_html(url) :
    html = ""
    resp = requests.get(url)

    if resp.status_code == 200 :
        html = resp.text
    return html
html = get_html('http://www.boonyang24.com/?sub=boonyang_info/info_list')
soup = BeautifulSoup(html, 'html.parser')  #해당 페이지 전체를 불러옴
boonyang = soup.find("div",{"class":"list_type_boonyang"})
#soup = 전체 페이지 불러옴
#boonyang은 그 중 테이블에 해당되는 곳 만 파싱
print(boonyang)
#필요한 정보 => 위치, 면적, 가격, 시기
import pandas as pd
ul_li = boonyang.find("ul", {"class":"top"})
ul_li.text
print(ul_li)
lis = ul_li.findAll("li") #ul안에 있는 li를 list에다가 넣어줌  [<li></li>....]
print(lis)
#for li in ul_li:  #ul안에 있는 li를 파싱
#    print(li)
lis[0].text

lis_col = []
lis_col.extend(lis[2])
lis_col.extend(lis[3])
lis_col.extend(lis[4])
lis_col.extend(lis[6])
#내가 필요한 열의 종류는 지역(사업명/위치), 규모(면적), 가격, 연도(분양/입주시기)) 
print(lis_col)
lis_col[0] = '지역명'
lis_col[1] = '규모구분'
lis_col[3] = '연도'
print(lis_col)

lis_col_frame = pd.DataFrame(lis_col)
lis_col_frame
#lis_col을 표로 나타낼 열의 정보로 가공하였다.
Citycell = {}

#지역에 대한 리스트
w_city = soup.find_all('td', {'class':'subject'})
#다 서울이기 때문에 모든 리스트의 요소를 '서울'로 간단하게 바꿔줌. 

w_city_l = []

for i in range(0, 15):
    w_city[i]
    print(w_city[i].text)
print('\n')

for i in range(0, 15):
    w_city[i] = "서울"
    
del w_city[3]    #면적이 미정인 지역에 대해 리스트요소 제거.
del w_city[9]
print(w_city)
for i in range(0, 13):
    w_city_l.append(w_city[i])
print('\n')
print(w_city_l)

#연도에 대한 리스트 필요.
w_year = []


#pandas처리 내용
Citycell['지역명'] = w_city_l
sd = pd.DataFrame(Citycell)
sd = sd[['지역명']]

#규모에 대한 리스트
#에를 들어 면적이 80~149㎡의 경우 149㎡(가장 큰 평수일 경우)를 기준으로 잡았다.
#규모가 '미정일 경우엔 잡지않음.'
#첫페이지 미정 2개..
#전용면적 60㎡이하, 전용면적 60㎡초과 85㎡이하, 
#전용면적 85㎡초과 102㎡이하, 전용면적 102㎡초과

w_size = soup.find_all('b')
w_size_l = []    #규모구분정보를 리스트에 담음..
for i in range(0, 12):
    del w_size[i]
    
w_size[0] = "전용면적 102㎡초과"
w_size[1] = "전용면적 60㎡이하"
w_size[2] = "전용면적 102㎡초과"
w_size[3] = "전용면적 60㎡초과 85㎡이하"
w_size[4] = "전용면적 85㎡초과 102㎡이하"
w_size[5] = "전용면적 102㎡초과"
w_size[6] = "전용면적 60㎡이하"
w_size[7] = "전용면적 102㎡초과"
w_size[8] = "전용면적 60㎡이하"
w_size[9] = "전용면적 60㎡이하"
w_size[10] = "전용면적 60㎡이하"
w_size[11] = "전용면적 102㎡초과"
w_size[12] = "전용면적 102㎡초과"

print(w_size)
for i in range(0, 13):
    w_size_l.append(w_size[i])

#pandas처리 내용
Citycell['지역명'] = w_city_l
Citycell['규모구분'] = w_size_l

sd = pd.DataFrame(Citycell)
sd = sd[['지역명', '규모구분']]

#가격에 대한 리스트
print('\n')
w_price = soup.find_all('p')
print(w_price)               #6번째 주기로 가격정보가 나오는걸 알 수 있다.
                            #'미정'처리된 두 지역은 빼고 생각하였다.

print('\n')
print("[가공 전 내용.]\n")
for i in range(1,16):
    print(w_price[6*i-1].text)    
print('\n')

w_price_l = []

#3번째, 9번째 항목을 없애줘야 한다.
print("[가공 후 내용.]\n")

for i in range(1,4):
    print(w_price[6*i-1].text)   
    w_price_l.extend(w_price[6*i-1])   #등차수열 이용.
for i in range(5,10):
    print(w_price[6*i-1].text)
    w_price_l.extend(w_price[6*i-1])
for i in range(11,16):
    print(w_price[6*i-1].text)
    w_price_l.extend(w_price[6*i-1])
print('\n')
print(w_price_l)
    

#pandas처리 내용
Citycell['지역명'] = w_city_l
Citycell['규모구분'] = w_size_l
Citycell['분양가격'] = w_price_l

sd = pd.DataFrame(Citycell)
sd = sd[['지역명', '규모구분','분양가격']]

w_price_l[0] = 1947700
w_price_l[1] = 171960
w_price_l[2] = 1385000
w_price_l[3] = 85120
w_price_l[4] = 1289000
w_price_l[5] = 890000
w_price_l[6] = 345000
w_price_l[7] = 2277000
w_price_l[8] = 350500
w_price_l[9] = 240000
w_price_l[10] = 316200
w_price_l[11] = 661000
w_price_l[12] = 826400
print('\n')
print(w_price_l)


#pandas처리 내용
sd = pd.DataFrame(Citycell)
sd = sd[['지역명', '규모구분','분양가격']]

#평당분양가격
sd['분양가격'] = pd.to_numeric(w_price_l, errors = 'coerce')

#w_square = 평당분양가격
w_square = []

for i in range(0, 13):
    w_square.append(w_price_l[i])
print(w_square)
w_square[0] = int(1947700/102)
w_square[1] = int(171960/60)
w_square[2] = int(1385000/102)
w_square[3] = int(85120/85)
w_square[4] = int(1289000/102)
w_square[5] = int(890000/102)
w_square[6] = int(345000/60)
w_square[7] = int(2277000/102)
w_square[8] = int(350500/60)
w_square[9] = int(240000/60)
w_square[10] = int(316200/60)
w_square[11] = int(661000/102)
w_square[12] = int(826400/102)



#pandas처리 내용
Citycell['평당분양가격'] = w_square

sd = pd.DataFrame(Citycell)
sd = sd[['지역명', '규모구분','분양가격','평당분양가격']]

#연도에 대한 리스트 필요.
print("[가공 전 내용.]\n")
w_year = soup.find_all('p')
print(w_year)
#가격과 연도는 같은 <p>태그 안에 있다.
#분양가를 알아보는 프로젝트 이므로 입주일이 아닌 분양일 기준으로 리스트를 정리할 계획이다.
print('\n')

#7, 13, 19, 25 a+(n-1)d
#7+(i-1)*6        // 등차수열 이용.
#가공하여 넣을 리스트 만들기.
w_year_l = []

for i in range(1,16):
    print(w_year[7+(i-1)*6].text)    
    w_year_l.extend(w_year[7+(i-1)*6])
    
print("\n[가공 중인 내용.]\n")
print(w_year_l)
print('\n')

#'미정' 제거
del w_year_l[3]
del w_year_l[9]
print(w_year_l)
for i in range(0,6):
    w_year_l[i] = '2019'
for i in range(6,13):
    w_year_l[i] = '2018'

print("\n[가공 후 내용.]\n")
print(w_year_l)



#pandas처리 내용
Citycell['지역명'] = w_city_l
Citycell['규모구분'] = w_size_l
Citycell['가격'] = w_price_l
Citycell['연도'] = w_year_l

sd = pd.DataFrame(Citycell)
sd = sd[['지역명', '규모구분','분양가격','평당분양가격', '연도']]

<div class="list_type_boonyang">
<ul class="top">
<li style="width:10%;">사업단계</li>
<li style="width:12%;">분양종류/형태</li>
<li style="width:30%;">사업명/위치</li>
<li style="width:12%;">면적</li>
<li style="width:10%;">가격</li>
<li style="width:12%;">세대수</li>
<li style="width:14%;">분양/입주시기</li>
</ul>
<table>
<caption>현장정보</caption>
<colgroup>
<col width="10%"/>
<col width="12%"/>
<col width="*"/>
<col width="12%"/>
<col width="10%"/>
<col width="12%"/>
<col width="14%"/>
</colgroup>
<tbody>
<tr class="info_list" idx_no="989">
<td><p class="tag_blue">분양중</p></td>
<td><p>오피스텔</p><span>민간분양</span></td>
<td class="subject"><strong>여의도아리스타 </strong><span>서울특별시 영등포구 당산동 121-61</span></td>
<td><b title="8 평">29</b>~<b title="15 평">50</b>  ㎡</td>
<td><p>21,100 ~ 37,500만원</p></td>
<td><p>306 세대</p></td>
<td><p>2019.06 분양</p><p>2021.10 입주</p></td>
</tr>
<tr class="info_list" idx_no="976">
<td><p class="tag_blue">분양중</p></td>
<td><p>아파트</p><span>민간분양</span></td>
<td class="subject"><strong>디에이치포레센트 </strong><span>서울특별시 강남구 일원동 690-1</span></td>
<td><b title="24 평">80</b>~<b title="45 평">149</b>  ㎡</td>
<td><p>132,150 ~ 194,770만원</p></td>
<td><p>184 세대</p></td>
<td><p>2019.04 분양</p><p>2021.01 입주</p></td>
</tr>
<tr class="info_list" idx_no="966">
<td><p class="tag_blue">분양중</p></td>
<td><p>오피스텔</p><span>민간분양</span></td>
<td class="subject"><strong>방학신화하니엘시티 </strong><span>서울특별시 도봉구 방학동 711-1</span></td>
<td><b title="7 평">25</b>~<b title="8 평">26</b>  ㎡</td>
<td><p>17,302 ~ 17,196만원</p></td>
<td><p>315 세대</p></td>
<td><p>2019.04 분양</p><p>2021.05 입주</p></td>
</tr>
<tr class="info_list" idx_no="961">
<td><p class="tag_blue">분양중</p></td>
<td><p>아파트</p><span>민간분양</span></td>
<td class="subject"><strong>청량리역해링턴플레이스 </strong><span>서울특별시 동대문구 용두동 11-1</span></td>
<td><b title="25 평">83</b>~<b title="62 평">207</b>  ㎡</td>
<td><p>69,000 ~ 138,500만원</p></td>
<td><p>220 세대</p></td>
<td><p>2019.04 분양</p><p>2023.01 입주</p></td>
</tr>
<tr class="info_list" idx_no="951">
<td><p class="tag_blue">분양중</p></td>
<td><p>상가</p><span>민간분양</span></td>
<td class="subject"><strong>마곡메가타워 </strong><span>서울시 강서구 마곡동 728-247</span></td>
<td>미정  ㎡</td>
<td><p>미정 만원</p></td>
<td><p>111 점포</p></td>
<td><p>2019.02 분양</p><p>2020.08 입주</p></td>
</tr>
<tr class="info_list" idx_no="933">
<td><p class="tag_blue">분양중</p></td>
<td><p>아파트</p><span>민간분양</span></td>
<td class="subject"><strong>시티프라디움더강남(1BL) </strong><span>서울특별시 강남구 역삼동 654-4</span></td>
<td><b title="25 평">84</b>~<b title="25 평">85</b>  ㎡</td>
<td><p>111,700 ~ 8,512만원</p></td>
<td><p>72 세대</p></td>
<td><p>2019.01 분양</p><p>2020.06 입주</p></td>
</tr>
<tr class="info_list" idx_no="934">
<td><p class="tag_blue">분양중</p></td>
<td><p>아파트</p><span>민간분양</span></td>
<td class="subject"><strong>시티프라디움더강남(2BL) </strong><span>서울특별시 강남구 역삼동 654</span></td>
<td><b title="29 평">97</b>  ㎡</td>
<td><p>128,900만원</p></td>
<td><p>34 세대</p></td>
<td><p>2019.01 분양</p><p>2021.06 입주</p></td>
</tr>
<tr class="info_list" idx_no="927">
<td><p class="tag_blue">분양중</p></td>
<td><p>아파트</p><span>민간분양</span></td>
<td class="subject"><strong>DMC SK뷰 </strong><span>서울특별시 은평구증산서길 1-17 일대</span></td>
<td><b title="25 평">84</b>~<b title="45 평">149</b>  ㎡</td>
<td><p>47,500 ~ 89,000만원</p></td>
<td><p>753 세대</p></td>
<td><p>2018.12 분양</p><p>2021.10 입주</p></td>
</tr>
<tr class="info_list" idx_no="929">
<td><p class="tag_blue">분양중</p></td>
<td><p>아파트</p><span>민간분양</span></td>
<td class="subject"><strong>서울DS이즈빌 </strong><span>서울특별시 강동구 길동 456-4</span></td>
<td><b title="6 평">20</b>~<b title="9 평">30</b>  ㎡</td>
<td><p>22,000 ~ 34,500만원</p></td>
<td><p>105 세대</p></td>
<td><p>2018.12 분양</p><p>2019.01 입주</p></td>
</tr>
<tr class="info_list" idx_no="924">
<td><p class="tag_blue">분양중</p></td>
<td><p>아파트</p><span>민간분양</span></td>
<td class="subject"><strong>디에이치라클라스 </strong><span>서울특별시 서초구 반포동 32-8</span></td>
<td><b title="20 평">69</b>~<b title="52 평">173</b>  ㎡</td>
<td><p>103,600 ~ 227,700만원</p></td>
<td><p>848 세대</p></td>
<td><p>2018.12 분양</p><p>2021.05 입주</p></td>
</tr>
<tr class="info_list" idx_no="926">
<td><p class="tag_blue">분양중</p></td>
<td><p>상가</p><span>민간분양</span></td>
<td class="subject"><strong>마곡역류마타워Ⅱ </strong><span>서울시 강서구 마곡지구 C12-3,4</span></td>
<td>미정  ㎡</td>
<td><p>미정 만원</p></td>
<td><p>197 점포</p></td>
<td><p>2018.12 분양</p><p>2019.10 입주</p></td>
</tr>
<tr class="info_list" idx_no="919">
<td><p class="tag_blue">분양중</p></td>
<td><p>아파트</p><span>민간분양</span></td>
<td class="subject"><strong>독산동오르페움타워 </strong><span>서울특별시 금천구 독산동 989</span></td>
<td><b title="16 평">55</b>~<b title="17 평">59</b>  ㎡</td>
<td><p>33,737 ~ 35,050만원</p></td>
<td><p>68 세대</p></td>
<td><p>2018.11 분양</p><p>2020.08 입주</p></td>
</tr>
<tr class="info_list" idx_no="962">
<td><p class="tag_blue">분양중</p></td>
<td><p>오피스텔</p><span>민간분양</span></td>
<td class="subject"><strong>청계다우아트리체디벨2차 </strong><span>서울시 동대문구 용두동 255-70</span></td>
<td><b title="9 평">31</b>~<b title="12 평">41</b>  ㎡</td>
<td><p>18,000 ~ 24,000만원</p></td>
<td><p>150 세대</p></td>
<td><p>2018.10 분양</p><p>2020.10 입주</p></td>
</tr>
<tr class="info_list" idx_no="877">
<td><p class="tag_blue">분양중</p></td>
<td><p>오피스텔</p><span>민간분양</span></td>
<td class="subject"><strong>여의도리슈빌DS </strong><span>서울특별시 영등포구 영등포동1가 121-</span></td>
<td><b title="9 평">31</b>~<b title="12 평">40</b>  ㎡</td>
<td><p>24,870 ~ 31,620만원</p></td>
<td><p>310 세대</p></td>
<td><p>2018.07 분양</p><p>2020.11 입주</p></td>
</tr>
<tr class="info_list" idx_no="871">
<td><p class="tag_blue">분양중</p></td>
<td><p>아파트</p><span>민간분양</span></td>
<td class="subject"><strong>꿈의숲아이파크 </strong><span>서울특별시 성북구 장위동 189-3</span></td>
<td><b title="25 평">84</b>~<b title="42 평">140</b>  ㎡</td>
<td><p>47,500 ~ 66,100만원</p></td>
<td><p>1,711 세대</p></td>
<td><p>2018.07 분양</p><p>2020.12 입주</p></td>
</tr>
</tbody>
</table>
</div>
<ul class="top">
<li style="width:10%;">사업단계</li>
<li style="width:12%;">분양종류/형태</li>
<li style="width:30%;">사업명/위치</li>
<li style="width:12%;">면적</li>
<li style="width:10%;">가격</li>
<li style="width:12%;">세대수</li>
<li style="width:14%;">분양/입주시기</li>
</ul>
[<li style="width:10%;">사업단계</li>, <li style="width:12%;">분양종류/형태</li>, <li style="width:30%;">사업명/위치</li>, <li style="width:12%;">면적</li>, <li style="width:10%;">가격</li>, <li style="width:12%;">세대수</li>, <li style="width:14%;">분양/입주시기</li>]
['사업명/위치', '면적', '가격', '분양/입주시기']
['지역명', '규모구분', '가격', '연도']
여의도아리스타 서울특별시 영등포구 당산동 121-61
디에이치포레센트 서울특별시 강남구 일원동 690-1
방학신화하니엘시티 서울특별시 도봉구 방학동 711-1
청량리역해링턴플레이스 서울특별시 동대문구 용두동 11-1
마곡메가타워 서울시 강서구 마곡동 728-247
시티프라디움더강남(1BL) 서울특별시 강남구 역삼동 654-4
시티프라디움더강남(2BL) 서울특별시 강남구 역삼동 654
DMC SK뷰 서울특별시 은평구증산서길 1-17 일대
서울DS이즈빌 서울특별시 강동구 길동 456-4
디에이치라클라스 서울특별시 서초구 반포동 32-8
마곡역류마타워Ⅱ 서울시 강서구 마곡지구 C12-3,4
독산동오르페움타워 서울특별시 금천구 독산동 989
청계다우아트리체디벨2차 서울시 동대문구 용두동 255-70
여의도리슈빌DS 서울특별시 영등포구 영등포동1가 121-
꿈의숲아이파크 서울특별시 성북구 장위동 189-3


['서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울']


['서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울']
['전용면적 102㎡초과', '전용면적 60㎡이하', '전용면적 102㎡초과', '전용면적 60㎡초과 85㎡이하', '전용면적 85㎡초과 102㎡이하', '전용면적 102㎡초과', '전용면적 60㎡이하', '전용면적 102㎡초과', '전용면적 60㎡이하', '전용면적 60㎡이하', '전용면적 60㎡이하', '전용면적 102㎡초과', '전용면적 102㎡초과']


[<p class="arrow"></p>, <p class="arrow"></p>, <p class="arrow"></p>, <p class="tag_blue">분양중</p>, <p>오피스텔</p>, <p>21,100 ~ 37,500만원</p>, <p>306 세대</p>, <p>2019.06 분양</p>, <p>2021.10 입주</p>, <p class="tag_blue">분양중</p>, <p>아파트</p>, <p>132,150 ~ 194,770만원</p>, <p>184 세대</p>, <p>2019.04 분양</p>, <p>2021.01 입주</p>, <p class="tag_blue">분양중</p>, <p>오피스텔</p>, <p>17,302 ~ 17,196만원</p>, <p>315 세대</p>, <p>2019.04 분양</p>, <p>2021.05 입주</p>, <p class="tag_blue">분양중</p>, <p>아파트</p>, <p>69,000 ~ 138,500만원</p>, <p>220 세대</p>, <p>2019.04 분양</p>, <p>2023.01 입주</p>, <p class="tag_blue">분양중</p>, <p>상가</p>, <p>미정 만원</p>, <p>111 점포</p>, <p>2019.02 분양</p>, <p>2020.08 입주</p>, <p class="tag_blue">분양중</p>, <p>아파트</p>, <p>111,700 ~ 8,512만원</p>, <p>72 세대</p>, <p>2019.01 분양</p>, <p>2020.06 입주</p>, <p class="tag_blue">분양중</p>, <p>아파트</p>, <p>128,900만원</p>, <p>34 세대</p>, <p>2019.01 분양</p>, <p>2021.06 입주</p>, <p class="tag_blue">분양중</p>, <p>아파트</p>, <p>47,500 ~ 89,000만원</p>, <p>753 세대</p>, <p>2018.12 분양</p>, <p>2021.10 입주</p>, <p class="tag_blue">분양중</p>, <p>아파트</p>, <p>22,000 ~ 34,500만원</p>, <p>105 세대</p>, <p>2018.12 분양</p>, <p>2019.01 입주</p>, <p class="tag_blue">분양중</p>, <p>아파트</p>, <p>103,600 ~ 227,700만원</p>, <p>848 세대</p>, <p>2018.12 분양</p>, <p>2021.05 입주</p>, <p class="tag_blue">분양중</p>, <p>상가</p>, <p>미정 만원</p>, <p>197 점포</p>, <p>2018.12 분양</p>, <p>2019.10 입주</p>, <p class="tag_blue">분양중</p>, <p>아파트</p>, <p>33,737 ~ 35,050만원</p>, <p>68 세대</p>, <p>2018.11 분양</p>, <p>2020.08 입주</p>, <p class="tag_blue">분양중</p>, <p>오피스텔</p>, <p>18,000 ~ 24,000만원</p>, <p>150 세대</p>, <p>2018.10 분양</p>, <p>2020.10 입주</p>, <p class="tag_blue">분양중</p>, <p>오피스텔</p>, <p>24,870 ~ 31,620만원</p>, <p>310 세대</p>, <p>2018.07 분양</p>, <p>2020.11 입주</p>, <p class="tag_blue">분양중</p>, <p>아파트</p>, <p>47,500 ~ 66,100만원</p>, <p>1,711 세대</p>, <p>2018.07 분양</p>, <p>2020.12 입주</p>, <p>아파트</p>, <p>아파트</p>, <p>아파트</p>, <p>아파트</p>, <p>아파트</p>, <p>제호 [ 분양정보닷컴 ]</p>, <p>고객센터</p>]


[가공 전 내용.]

21,100 ~ 37,500만원
132,150 ~ 194,770만원
17,302 ~ 17,196만원
69,000 ~ 138,500만원
미정 만원
111,700 ~ 8,512만원
128,900만원
47,500 ~ 89,000만원
22,000 ~ 34,500만원
103,600 ~ 227,700만원
미정 만원
33,737 ~ 35,050만원
18,000 ~ 24,000만원
24,870 ~ 31,620만원
47,500 ~ 66,100만원


[가공 후 내용.]

21,100 ~ 37,500만원
132,150 ~ 194,770만원
17,302 ~ 17,196만원
미정 만원
111,700 ~ 8,512만원
128,900만원
47,500 ~ 89,000만원
22,000 ~ 34,500만원
미정 만원
33,737 ~ 35,050만원
18,000 ~ 24,000만원
24,870 ~ 31,620만원
47,500 ~ 66,100만원


['21,100 ~ 37,500만원', '132,150 ~ 194,770만원', '17,302 ~ 17,196만원', '미정 만원', '111,700 ~ 8,512만원', '128,900만원', '47,500 ~ 89,000만원', '22,000 ~ 34,500만원', '미정 만원', '33,737 ~ 35,050만원', '18,000 ~ 24,000만원', '24,870 ~ 31,620만원', '47,500 ~ 66,100만원']


[1947700, 171960, 1385000, 85120, 1289000, 890000, 345000, 2277000, 350500, 240000, 316200, 661000, 826400]
[1947700, 171960, 1385000, 85120, 1289000, 890000, 345000, 2277000, 350500, 240000, 316200, 661000, 826400]
[가공 전 내용.]

[<p class="arrow"></p>, <p class="arrow"></p>, <p class="arrow"></p>, <p class="tag_blue">분양중</p>, <p>오피스텔</p>, <p>21,100 ~ 37,500만원</p>, <p>306 세대</p>, <p>2019.06 분양</p>, <p>2021.10 입주</p>, <p class="tag_blue">분양중</p>, <p>아파트</p>, <p>132,150 ~ 194,770만원</p>, <p>184 세대</p>, <p>2019.04 분양</p>, <p>2021.01 입주</p>, <p class="tag_blue">분양중</p>, <p>오피스텔</p>, <p>17,302 ~ 17,196만원</p>, <p>315 세대</p>, <p>2019.04 분양</p>, <p>2021.05 입주</p>, <p class="tag_blue">분양중</p>, <p>아파트</p>, <p>69,000 ~ 138,500만원</p>, <p>220 세대</p>, <p>2019.04 분양</p>, <p>2023.01 입주</p>, <p class="tag_blue">분양중</p>, <p>상가</p>, <p>미정 만원</p>, <p>111 점포</p>, <p>2019.02 분양</p>, <p>2020.08 입주</p>, <p class="tag_blue">분양중</p>, <p>아파트</p>, <p>111,700 ~ 8,512만원</p>, <p>72 세대</p>, <p>2019.01 분양</p>, <p>2020.06 입주</p>, <p class="tag_blue">분양중</p>, <p>아파트</p>, <p>128,900만원</p>, <p>34 세대</p>, <p>2019.01 분양</p>, <p>2021.06 입주</p>, <p class="tag_blue">분양중</p>, <p>아파트</p>, <p>47,500 ~ 89,000만원</p>, <p>753 세대</p>, <p>2018.12 분양</p>, <p>2021.10 입주</p>, <p class="tag_blue">분양중</p>, <p>아파트</p>, <p>22,000 ~ 34,500만원</p>, <p>105 세대</p>, <p>2018.12 분양</p>, <p>2019.01 입주</p>, <p class="tag_blue">분양중</p>, <p>아파트</p>, <p>103,600 ~ 227,700만원</p>, <p>848 세대</p>, <p>2018.12 분양</p>, <p>2021.05 입주</p>, <p class="tag_blue">분양중</p>, <p>상가</p>, <p>미정 만원</p>, <p>197 점포</p>, <p>2018.12 분양</p>, <p>2019.10 입주</p>, <p class="tag_blue">분양중</p>, <p>아파트</p>, <p>33,737 ~ 35,050만원</p>, <p>68 세대</p>, <p>2018.11 분양</p>, <p>2020.08 입주</p>, <p class="tag_blue">분양중</p>, <p>오피스텔</p>, <p>18,000 ~ 24,000만원</p>, <p>150 세대</p>, <p>2018.10 분양</p>, <p>2020.10 입주</p>, <p class="tag_blue">분양중</p>, <p>오피스텔</p>, <p>24,870 ~ 31,620만원</p>, <p>310 세대</p>, <p>2018.07 분양</p>, <p>2020.11 입주</p>, <p class="tag_blue">분양중</p>, <p>아파트</p>, <p>47,500 ~ 66,100만원</p>, <p>1,711 세대</p>, <p>2018.07 분양</p>, <p>2020.12 입주</p>, <p>아파트</p>, <p>아파트</p>, <p>아파트</p>, <p>아파트</p>, <p>아파트</p>, <p>제호 [ 분양정보닷컴 ]</p>, <p>고객센터</p>]


2019.06 분양
2019.04 분양
2019.04 분양
2019.04 분양
2019.02 분양
2019.01 분양
2019.01 분양
2018.12 분양
2018.12 분양
2018.12 분양
2018.12 분양
2018.11 분양
2018.10 분양
2018.07 분양
2018.07 분양

[가공 중인 내용.]

['2019.06 분양', '2019.04 분양', '2019.04 분양', '2019.04 분양', '2019.02 분양', '2019.01 분양', '2019.01 분양', '2018.12 분양', '2018.12 분양', '2018.12 분양', '2018.12 분양', '2018.11 분양', '2018.10 분양', '2018.07 분양', '2018.07 분양']


['2019.06 분양', '2019.04 분양', '2019.04 분양', '2019.02 분양', '2019.01 분양', '2019.01 분양', '2018.12 분양', '2018.12 분양', '2018.12 분양', '2018.11 분양', '2018.10 분양', '2018.07 분양', '2018.07 분양']

[가공 후 내용.]

['2019', '2019', '2019', '2019', '2019', '2019', '2018', '2018', '2018', '2018', '2018', '2018', '2018']

In [43]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

def get_html(url) :
    html = ""
    resp = requests.get(url)
    if resp.status_code == 200 :
        html = resp.text
    return html
html = get_html('http://www.boonyang24.com/?sub=boonyang_info/info_list&do1=&si1=&boonryu01=&boonryu02=&page=2&keyword=&tp=&cate=&area_code=&work_year=&hyun_cate=')
soup = BeautifulSoup(html, 'html.parser')
boonyang = soup.find("div",{"class":"list_type_boonyang"})
#----------------------------------------------------------------------

Citycell = {}

#지역에 대한 리스트
w_city1 = soup.find_all('td', {'class':'subject'})
#다 서울이기 때문에 모든 리스트의 요소를 '서울'로 간단하게 바꿔줌. 

for i in range(0, 15):   #0~14
    w_city1[i]
    print(w_city1[i].text)
print('\n')

for i in range(0, 15):
    w_city1[i] = "서울"
for i in range(0, 15):
    w_city_l.append(w_city1[i])
    
print(w_city_l)
print('\n')

Citycell['지역명'] = w_city_l

sd = pd.DataFrame(Citycell)
sd = sd[['지역명']]

#----------------------------------------------------------------------
w_size1 = soup.find_all('b')
for i in range(0, 14):
    del w_size1[i]
#"전용면적 60㎡이하"
#"전용면적 102㎡초과"
#"전용면적 60㎡초과 85㎡이하"
#"전용면적 85㎡초과 102㎡이하"
w_size1[0] = "전용면적 60㎡이하"
w_size1[1] = "전용면적 102㎡초과"
w_size1[2] = "전용면적 102㎡초과"
w_size1[3] = "전용면적 60㎡이하"
w_size1[4] = "전용면적 60㎡이하"
w_size1[5] = "전용면적 102㎡초과"
w_size1[6] = "전용면적 60㎡초과 85㎡이하"
w_size1[7] = "전용면적 102㎡초과"
w_size1[8] = "전용면적 60㎡초과 85㎡이하"
w_size1[9] = "전용면적 102㎡초과"
w_size1[10] = "전용면적 102㎡초과"
w_size1[11] = "전용면적 102㎡초과"
w_size1[12] = "전용면적 60㎡이하"
w_size1[13] = "전용면적 102㎡초과"
w_size1[14] = "전용면적 102㎡초과"
print(w_size1)

for i in range(0, 15):
    w_size_l.append(w_size1[i])

print(w_size_l)

Citycell['지역명'] = w_city_l
Citycell['규모구분'] = w_size_l
sd = pd.DataFrame(Citycell)
sd = sd[['지역명', '규모구분']]

#----------------------------------------------------------------------
print('\n')
w_price1 = soup.find_all('p')
print(w_price1)               #6번째 주기로 가격정보가 나오는걸 알 수 있다.
                            #'미정'처리된 두 지역은 빼고 생각하였다.
print('\n')

for i in range(1,16):
    print(w_price1[6*i-1].text)   
    w_price_l.extend(w_price1[6*i-1])   #등차수열 이용.
print('\n')
print(w_price_l)
    
Citycell['지역명'] = w_city_l
Citycell['규모구분'] = w_size_l
Citycell['분양가격'] = w_price_l
sd = pd.DataFrame(Citycell)

sd = sd[['지역명', '규모구분','분양가격']]

#----------------------------------------------------------------------

#크롤링한 사이트는 단위가 '만 원'이다.
#본래 데이터분석을 한 자료의 단위는 '천 원'이므로 끝에 0을 더 붙여서 할당하였다.
w_price_l[13] = 350290
w_price_l[14] = 681580
w_price_l[15] = 828000
w_price_l[16] = 356800
w_price_l[17] = 289800
w_price_l[18] = 497100
w_price_l[19] = 399000
w_price_l[20] = 1058280
w_price_l[21] = 2500000
w_price_l[22] = 731100
w_price_l[23] = 648500
w_price_l[24] = 723300
w_price_l[25] = 149900
w_price_l[26] = 585200
w_price_l[27] = 552800
print('\n')
print(w_price_l)

sd = pd.DataFrame(Citycell)
sd = sd[['지역명', '규모구분','분양가격']]


#----------------------------------------------------------------------

#평당분양가격
sd['분양가격'] = pd.to_numeric(w_price_l, errors = 'coerce')


for i in range(13, 28):
    w_square.append(w_price_l[i])
print(w_square)
w_square[13] = int(350290/60)
w_square[14] = int(681580/102)
w_square[15] = int(828000/102)
w_square[16] = int(356800/60)
w_square[17] = int(289800/60)
w_square[18] = int(497100/102)
w_square[19] = int(399000/85)
w_square[20] = int(1058280/102)
w_square[21] = int(2500000/85)
w_square[22] = int(731100/102)
w_square[23] = int(648500/102)
w_square[24] = int(723300/102)
w_square[25] = int(149900/60)
w_square[26] = int(585200/102)
w_square[27] = int(552800/102)


Citycell['평당분양가격'] = w_square
sd = pd.DataFrame(Citycell)
sd = sd[['지역명', '규모구분','분양가격','평당분양가격']]


#----------------------------------------------------------------------

#연도에 대한 리스트 필요.
w_year1 = soup.find_all('p')
print(w_year1)
#가격과 연도는 같은 <p>태그 안에 있다.
#분양가를 알아보는 프로젝트 이므로 입주일이 아닌 분양일 기준으로 리스트를 정리할 계획이다.
print('\n')
#7, 13, 19, 25 a+(n-1)d
#7+(i-1)*6        // 등차수열 이용.
for i in range(1,16):
    print(w_year1[7+(i-1)*6].text)    
    w_year_l.extend(w_year1[7+(i-1)*6])
    

print('\n')
print(w_year_l)

w_year_l[13] = '2018'
for i in range(14,28):
    w_year_l[i] = '2017'
print('\n')
print(w_year_l)

Citycell['지역명'] = w_city_l
Citycell['규모구분'] = w_size_l
Citycell['가격'] = w_price_l
Citycell['연도'] = w_year_l

sd = pd.DataFrame(Citycell)
sd = sd[['지역명', '규모구분','분양가격','평당분양가격', '연도']]
sd

#----------------------------------------------------------------------

신길파크자이 서울특별시 영등포구 신길동 3163
사보이시티잠실 서울시 송파구 방이동 42-2,4,5 번지
e편한세상강동에코포레 서울특별시 강동구 길동 43
힐스테이트클래시안 서울특별시 영등포구 신길동 240-16
잠실벨솔레 서울특별시 송파구 방이동 41-8
가산센트럴푸르지오시티 서울특별시 금천구 가산동 233-5
서울항동제일풍경채(7BL) 서울특별시 구로구 항동 7BL
북한산두산위브2차 서울특별시 서대문구 홍은 1동 13-25번
고덕아르테온 서울특별시 강동구 상일동 121
문래롯데캐슬(뉴스테이) 서울특별시 영등포구 문래동6가 21
녹번역e편한세상캐슬 서울특별시 은평구 응암동 36, 37, 53번
백련산해모로 서울특별시 은평구 응암동 455-25
사가정센트럴아이파크 서울특별시 중랑구 면목동 164-10
칸타빌레5차 서울특별시 구로구 오류동 59-20
면목라온프라이빗 서울특별시 중랑구 면목동 171-7


['서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울']


['전용면적 60㎡이하', '전용면적 102㎡초과', '전용면적 102㎡초과', '전용면적 60㎡이하', '전용면적 60㎡이하', '전용면적 102㎡초과', '전용면적 60㎡초과 85㎡이하', '전용면적 102㎡초과', '전용면적 60㎡초과 85㎡이하', '전용면적 102㎡초과', '전용면적 102㎡초과', '전용면적 102㎡초과', '전용면적 60㎡이하', '전용면적 102㎡초과', '전용면적 102㎡초과']
['전용면적 102㎡초과', '전용면적 60㎡이하', '전용면적 102㎡초과', '전용면적 60㎡초과 85㎡이하', '전용면적 85㎡초과 102㎡이하', '전용면적 102㎡초과', '전용면적 60㎡이하', '전용면적 102㎡초과', '전용면적 60㎡이하', '전용면적 60㎡이하', '전용면적 60㎡이하', '전용면적 102㎡초과', '전용면적 102㎡초과', '전용면적 60㎡이하', '전용면적 102㎡초과', '전용면적 102㎡초과', '전용면적 60㎡이하', '전용면적 60㎡이하', '전용면적 102㎡초과', '전용면적 60㎡초과 85㎡이하', '전용면적 102㎡초과', '전용면적 60㎡초과 85㎡이하', '전용면적 102㎡초과', '전용면적 102㎡초과', '전용면적 102㎡초과', '전용면적 60㎡이하', '전용면적 102㎡초과', '전용면적 102㎡초과']


[<p class="arrow"></p>, <p class="arrow"></p>, <p class="arrow"></p>, <p class="tag_blue">분양중</p>, <p>아파트</p>, <p>52,600 ~ 82,640만원</p>, <p>641 세대</p>, <p>2018.06 분양</p>, <p>2020.12 입주</p>, <p class="tag_blue">분양중</p>, <p>오피스텔</p>, <p>23,822 ~ 35,029만원</p>, <p>473 세대</p>, <p>2018.06 분양</p>, <p>2021.03 입주</p>, <p class="tag_blue">분양중</p>, <p>아파트</p>, <p>58,500 ~ 68,158만원</p>, <p>366 세대</p>, <p>2017.11 분양</p>, <p>2020.04 입주</p>, <p class="tag_blue">분양중</p>, <p>아파트</p>, <p>30,100 ~ 82,800만원</p>, <p>1,476 세대</p>, <p>2017.11 분양</p>, <p>2020.11 입주</p>, <p class="tag_blue">분양중</p>, <p>오피스텔</p>, <p>21,293 ~ 35,680만원</p>, <p>289 세대</p>, <p>2017.11 분양</p>, <p>2020.04 입주</p>, <p class="tag_blue">분양중</p>, <p>오피스텔</p>, <p>15,880 ~ 28,980만원</p>, <p>1,454 세대</p>, <p>2017.11 분양</p>, <p>2020.08 입주</p>, <p class="tag_blue">분양중</p>, <p>아파트</p>, <p>45,950 ~ 49,710만원</p>, <p>345 세대</p>, <p>2017.11 분양</p>, <p>2020.11 입주</p>, <p class="tag_blue">분양중</p>, <p>아파트</p>, <p>38,700 ~ 39,900만원</p>, <p>296 세대</p>, <p>2017.11 분양</p>, <p>2020.11 입주</p>, <p class="tag_blue">분양중</p>, <p>아파트</p>, <p>63,356 ~ 105,828만원</p>, <p>4,066 세대</p>, <p>2017.11 분양</p>, <p>2020.02 입주</p>, <p class="tag_blue">분양중</p>, <p>아파트</p>, <p>250,000천원</p>, <p>499 세대</p>, <p>2017.10 분양</p>, <p>2020.04 입주</p>, <p class="tag_blue">분양중</p>, <p>아파트</p>, <p>36,970 ~ 73,110만원</p>, <p>2,441 세대</p>, <p>2017.10 분양</p>, <p>2020.05 입주</p>, <p class="tag_blue">분양중</p>, <p>아파트</p>, <p>24,870 ~ 64,850만원</p>, <p>760 세대</p>, <p>2017.10 분양</p>, <p>2020.03 입주</p>, <p class="tag_blue">분양중</p>, <p>아파트</p>, <p>50,160 ~ 72,330만원</p>, <p>1,505 세대</p>, <p>2017.10 분양</p>, <p>2020.07 입주</p>, <p class="tag_blue">분양중</p>, <p>오피스텔</p>, <p>14,990만원</p>, <p>270 세대</p>, <p>2017.10 분양</p>, <p>2019.09 입주</p>, <p class="tag_blue">분양중</p>, <p>아파트</p>, <p>35,820 ~ 58,520만원</p>, <p>453 세대</p>, <p>2017.10 분양</p>, <p>2020.06 입주</p>, <p>아파트</p>, <p>아파트</p>, <p>아파트</p>, <p>아파트</p>, <p>아파트</p>, <p>제호 [ 분양정보닷컴 ]</p>, <p>고객센터</p>]


52,600 ~ 82,640만원
23,822 ~ 35,029만원
58,500 ~ 68,158만원
30,100 ~ 82,800만원
21,293 ~ 35,680만원
15,880 ~ 28,980만원
45,950 ~ 49,710만원
38,700 ~ 39,900만원
63,356 ~ 105,828만원
250,000천원
36,970 ~ 73,110만원
24,870 ~ 64,850만원
50,160 ~ 72,330만원
14,990만원
35,820 ~ 58,520만원


[1947700, 171960, 1385000, 85120, 1289000, 890000, 345000, 2277000, 350500, 240000, 316200, 661000, 826400, '52,600 ~ 82,640만원', '23,822 ~ 35,029만원', '58,500 ~ 68,158만원', '30,100 ~ 82,800만원', '21,293 ~ 35,680만원', '15,880 ~ 28,980만원', '45,950 ~ 49,710만원', '38,700 ~ 39,900만원', '63,356 ~ 105,828만원', '250,000천원', '36,970 ~ 73,110만원', '24,870 ~ 64,850만원', '50,160 ~ 72,330만원', '14,990만원', '35,820 ~ 58,520만원']


[1947700, 171960, 1385000, 85120, 1289000, 890000, 345000, 2277000, 350500, 240000, 316200, 661000, 826400, 350290, 681580, 828000, 356800, 289800, 497100, 399000, 1058280, 2500000, 731100, 648500, 723300, 149900, 585200, 552800]
[19095, 2866, 13578, 1001, 12637, 8725, 5750, 22323, 5841, 4000, 5270, 6480, 8101, 350290, 681580, 828000, 356800, 289800, 497100, 399000, 1058280, 2500000, 731100, 648500, 723300, 149900, 585200, 552800]
[<p class="arrow"></p>, <p class="arrow"></p>, <p class="arrow"></p>, <p class="tag_blue">분양중</p>, <p>아파트</p>, <p>52,600 ~ 82,640만원</p>, <p>641 세대</p>, <p>2018.06 분양</p>, <p>2020.12 입주</p>, <p class="tag_blue">분양중</p>, <p>오피스텔</p>, <p>23,822 ~ 35,029만원</p>, <p>473 세대</p>, <p>2018.06 분양</p>, <p>2021.03 입주</p>, <p class="tag_blue">분양중</p>, <p>아파트</p>, <p>58,500 ~ 68,158만원</p>, <p>366 세대</p>, <p>2017.11 분양</p>, <p>2020.04 입주</p>, <p class="tag_blue">분양중</p>, <p>아파트</p>, <p>30,100 ~ 82,800만원</p>, <p>1,476 세대</p>, <p>2017.11 분양</p>, <p>2020.11 입주</p>, <p class="tag_blue">분양중</p>, <p>오피스텔</p>, <p>21,293 ~ 35,680만원</p>, <p>289 세대</p>, <p>2017.11 분양</p>, <p>2020.04 입주</p>, <p class="tag_blue">분양중</p>, <p>오피스텔</p>, <p>15,880 ~ 28,980만원</p>, <p>1,454 세대</p>, <p>2017.11 분양</p>, <p>2020.08 입주</p>, <p class="tag_blue">분양중</p>, <p>아파트</p>, <p>45,950 ~ 49,710만원</p>, <p>345 세대</p>, <p>2017.11 분양</p>, <p>2020.11 입주</p>, <p class="tag_blue">분양중</p>, <p>아파트</p>, <p>38,700 ~ 39,900만원</p>, <p>296 세대</p>, <p>2017.11 분양</p>, <p>2020.11 입주</p>, <p class="tag_blue">분양중</p>, <p>아파트</p>, <p>63,356 ~ 105,828만원</p>, <p>4,066 세대</p>, <p>2017.11 분양</p>, <p>2020.02 입주</p>, <p class="tag_blue">분양중</p>, <p>아파트</p>, <p>250,000천원</p>, <p>499 세대</p>, <p>2017.10 분양</p>, <p>2020.04 입주</p>, <p class="tag_blue">분양중</p>, <p>아파트</p>, <p>36,970 ~ 73,110만원</p>, <p>2,441 세대</p>, <p>2017.10 분양</p>, <p>2020.05 입주</p>, <p class="tag_blue">분양중</p>, <p>아파트</p>, <p>24,870 ~ 64,850만원</p>, <p>760 세대</p>, <p>2017.10 분양</p>, <p>2020.03 입주</p>, <p class="tag_blue">분양중</p>, <p>아파트</p>, <p>50,160 ~ 72,330만원</p>, <p>1,505 세대</p>, <p>2017.10 분양</p>, <p>2020.07 입주</p>, <p class="tag_blue">분양중</p>, <p>오피스텔</p>, <p>14,990만원</p>, <p>270 세대</p>, <p>2017.10 분양</p>, <p>2019.09 입주</p>, <p class="tag_blue">분양중</p>, <p>아파트</p>, <p>35,820 ~ 58,520만원</p>, <p>453 세대</p>, <p>2017.10 분양</p>, <p>2020.06 입주</p>, <p>아파트</p>, <p>아파트</p>, <p>아파트</p>, <p>아파트</p>, <p>아파트</p>, <p>제호 [ 분양정보닷컴 ]</p>, <p>고객센터</p>]


2018.06 분양
2018.06 분양
2017.11 분양
2017.11 분양
2017.11 분양
2017.11 분양
2017.11 분양
2017.11 분양
2017.11 분양
2017.10 분양
2017.10 분양
2017.10 분양
2017.10 분양
2017.10 분양
2017.10 분양


['2019', '2019', '2019', '2019', '2019', '2019', '2018', '2018', '2018', '2018', '2018', '2018', '2018', '2018.06 분양', '2018.06 분양', '2017.11 분양', '2017.11 분양', '2017.11 분양', '2017.11 분양', '2017.11 분양', '2017.11 분양', '2017.11 분양', '2017.10 분양', '2017.10 분양', '2017.10 분양', '2017.10 분양', '2017.10 분양', '2017.10 분양']


['2019', '2019', '2019', '2019', '2019', '2019', '2018', '2018', '2018', '2018', '2018', '2018', '2018', '2018', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017']

   지역명               규모구분     분양가격  평당분양가격    연도
0   서울        전용면적 102㎡초과  1947700   19095  2019
1   서울         전용면적 60㎡이하   171960    2866  2019
2   서울        전용면적 102㎡초과  1385000   13578  2019
3   서울   전용면적 60㎡초과 85㎡이하    85120    1001  2019
4   서울  전용면적 85㎡초과 102㎡이하  1289000   12637  2019
5   서울        전용면적 102㎡초과   890000    8725  2019
6   서울         전용면적 60㎡이하   345000    5750  2018
7   서울        전용면적 102㎡초과  2277000   22323  2018
8   서울         전용면적 60㎡이하   350500    5841  2018
9   서울         전용면적 60㎡이하   240000    4000  2018
10  서울         전용면적 60㎡이하   316200    5270  2018
11  서울        전용면적 102㎡초과   661000    6480  2018
12  서울        전용면적 102㎡초과   826400    8101  2018
13  서울         전용면적 60㎡이하   350290    5838  2018
14  서울        전용면적 102㎡초과   681580    6682  2017
15  서울        전용면적 102㎡초과   828000    8117  2017
16  서울         전용면적 60㎡이하   356800    5946  2017
17  서울         전용면적 60㎡이하   289800    4830  2017
18  서울        전용면적 102㎡초과   497100    4873  2017
19  서울   전용면적 60㎡초과 85㎡이하   399000    4694  2017
20  서울        전용면적 102㎡초과  1058280   10375  2017
21  서울   전용면적 60㎡초과 85㎡이하  2500000   29411  2017
22  서울        전용면적 102㎡초과   731100    7167  2017
23  서울        전용면적 102㎡초과   648500    6357  2017
24  서울        전용면적 102㎡초과   723300    7091  2017
25  서울         전용면적 60㎡이하   149900    2498  2017
26  서울        전용면적 102㎡초과   585200    5737  2017
27  서울        전용면적 102㎡초과   552800    5419  2017

In [44]:
def get_html(url) :
    html = ""
    resp = requests.get(url)

    if resp.status_code == 200 :
        html = resp.text
    return html
html = get_html('http://www.boonyang24.com/?sub=boonyang_info/info_list&do1=&si1=&boonryu01=&boonryu02=&page=3&keyword=&tp=&cate=&area_code=&work_year=&hyun_cate=')
# print(html)

c = get_html('http://www.boonyang24.com/?sub=boonyang_info/info_list&do1=&si1=&boonryu01=&boonryu02=&page=3&keyword=&tp=&cate=&area_code=&work_year=&hyun_cate=')
soup = BeautifulSoup(c, 'html.parser')

boonyang = soup.find("div",{"class":"list_type_boonyang"})
#----------------------------------------------------------------------

#----------------------------------------------------------------------

Citycell = {}

#지역에 대한 리스트

w_city2 = soup.find_all('td', {'class':'subject'})
#다 서울이기 때문에 모든 리스트의 요소를 '서울'로 간단하게 바꿔줌. 

for i in range(0, 15):   #0~14
    w_city2[i]
    print(w_city2[i].text)
print('\n')

for i in range(0, 15):
    w_city2[i] = "서울"
for i in range(0, 15):
    w_city_l.append(w_city2[i])
    
print(w_city_l)
print('\n')

Citycell['지역명'] = w_city_l
sd = pd.DataFrame(Citycell)
sd = sd[['지역명']]

#----------------------------------------------------------------------
#규모에 대한 내용.
w_size2 = soup.find_all('b')
for i in range(0, 14):
    del w_size2[i]
w_size2[0] = "전용면적 102㎡초과"
w_size2[1] = "전용면적 60㎡이하"
w_size2[2] = "전용면적 102㎡초과"
w_size2[3] = "전용면적 60㎡이하"
w_size2[4] = "전용면적 60㎡초과 85㎡이하"
w_size2[5] = "전용면적 102㎡초과"
w_size2[6] = "전용면적 102㎡초과"
w_size2[7] = "전용면적 102㎡초과"
w_size2[8] = "전용면적 102㎡초과"
w_size2[9] = "전용면적 102㎡초과"
w_size2[10] = "전용면적 102㎡초과"
w_size2[11] = "전용면적 102㎡초과"
w_size2[12] = "전용면적 85㎡초과 102㎡이하"
w_size2[13] = "전용면적 102㎡초과"
w_size2[14] = "전용면적 102㎡초과"
print(w_size2)

for i in range(0, 15):
    w_size_l.append(w_size2[i])

print(w_size_l)

Citycell['지역명'] = w_city_l
Citycell['규모구분'] = w_size_l
sd = pd.DataFrame(Citycell)

sd = sd[['지역명', '규모구분']]

#----------------------------------------------------------------------
#
print('\n')
w_price2 = soup.find_all('p')
print(w_price2)               #6번째 주기로 가격정보가 나오는걸 알 수 있다.
                            #'미정'처리된 두 지역은 빼고 생각하였다.
print('\n')

for i in range(1,16):
    print(w_price2[6*i-1].text)   
    w_price_l.extend(w_price2[6*i-1])   #등차수열 이용.
print('\n')
print(w_price_l)
    
Citycell['지역명'] = w_city_l
Citycell['규모구분'] = w_size_l
Citycell['분양가격'] = w_price_l
sd = pd.DataFrame(Citycell)

sd = sd[['지역명', '규모구분','분양가격']]

#----------------------------------------------------------------------

#크롤링한 사이트는 단위가 '만 원'이다.
#본래 데이터분석을 한 자료의 단위는 '천 원'이므로 끝에 0을 더 붙여서 할당하였다.
w_price_l[28] = 729000
w_price_l[29] = 197000
w_price_l[30] = 739000
w_price_l[31] = 299000
w_price_l[32] = 596610
w_price_l[33] = 1043000
w_price_l[34] = 2178000
w_price_l[35] = 545000
w_price_l[36] = 546500
w_price_l[37] = 647400
w_price_l[38] = 2091500
w_price_l[39] = 547700
w_price_l[40] = 655600
w_price_l[41] = 1012000
w_price_l[42] = 685480
print('\n')
print(w_price_l)

sd = pd.DataFrame(Citycell)
sd = sd[['지역명', '규모구분','분양가격']]


#----------------------------------------------------------------------

#평당분양가격
sd['분양가격'] = pd.to_numeric(w_price_l, errors = 'coerce')


for i in range(28, 43):
    w_square.append(w_price_l[i])
print(w_square)
w_square[28] = int(729000/102)
w_square[29] = int(197000/60)
w_square[30] = int(739000/102)
w_square[31] = int(299000/60)
w_square[32] = int(596610/60)
w_square[33] = int(1043000/102)
w_square[34] = int(2178000/102)
w_square[35] = int(545000/102)
w_square[36] = int(546500/102)
w_square[37] = int(647400/102)
w_square[38] = int(2091500/102)
w_square[39] = int(547700/102)
w_square[40] = int(655600/85)
w_square[41] = int(1012000/102)
w_square[42] = int(685480/102)




Citycell['평당분양가격'] = w_square
sd = pd.DataFrame(Citycell)
sd = sd[['지역명', '규모구분','분양가격','평당분양가격']]


#----------------------------------------------------------------------

#연도에 대한 리스트 필요.
w_year2 = soup.find_all('p')
print(w_year2)
print('\n')
#7, 13, 19, 25 a+(n-1)d
#7+(i-1)*6        // 등차수열 이용.
for i in range(1,16):
    print(w_year2[7+(i-1)*6].text)    
    w_year_l.extend(w_year2[7+(i-1)*6])
    
print('\n')
print(w_year_l)

for i in range(28,43):
    w_year_l[i] = '2017'
print('\n')
print(w_year_l)

#pandas 처리
Citycell['지역명'] = w_city_l
Citycell['규모구분'] = w_size_l
Citycell['가격'] = w_price_l
Citycell['연도'] = w_year_l

sd = pd.DataFrame(Citycell)
sd = sd[['지역명', '규모구분','분양가격','평당분양가격', '연도']]
sd

#------------------------------------------------------------
#분양가격, 평당분양가격, 규모, 연도 같은 경우는 리스트의 요소 하나하나를 직접 다루는 중이다.

휘경해모로프레스티지 서울특별시 동대문구 휘경동 243
영등포뉴타운꿈에그린 서울특별시 영등포구 영등포동7가 29-1
창동 라르플레이스 서울특별시 도봉구 창동 749-15
래미안DMC루센티아 서울특별시 서대문구 거북골로 10길 19
잠실벨솔레 서울시 송파구 방이동 41-8외 5필지
서초센트럴IPARK(오) 서울특별시 서초구 서초동 1582-3
서초센트럴IPARK 서울특별시 서초구 서초동 1582-3 외 25
래미안강남포레스트 서울특별시 강남구 개포동 656
서울항동한양수자인와이즈파크 서울특별시 구로구 항동 154
한양수자인사가정파크 서울특별시 중랑구 면목동 520-19
장안태영데시앙 서울특별시 동대문구 장안동 291-1 일
신반포센트럴자이 서울특별시 서초구 잠원동 74-2
남성역동양라파크사당 서울시 동작구 사당동 235-81번지 일대
오금지구2단지(국민임대) 서울특별시 송파구 오금동 99
공덕SK리더스뷰 서울특별시 마포구 공덕동 385-65번지


['서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울']


['전용면적 102㎡초과', '전용면적 60㎡이하', '전용면적 102㎡초과', '전용면적 60㎡이하', '전용면적 60㎡초과 85㎡이하', '전용면적 102㎡초과', '전용면적 102㎡초과', '전용면적 102㎡초과', '전용면적 102㎡초과', '전용면적 102㎡초과', '전용면적 102㎡초과', '전용면적 102㎡초과', '전용면적 85㎡초과 102㎡이하', '전용면적 102㎡초과', '전용면적 102㎡초과']
['전용면적 102㎡초과', '전용면적 60㎡이하', '전용면적 102㎡초과', '전용면적 60㎡초과 85㎡이하', '전용면적 85㎡초과 102㎡이하', '전용면적 102㎡초과', '전용면적 60㎡이하', '전용면적 102㎡초과', '전용면적 60㎡이하', '전용면적 60㎡이하', '전용면적 60㎡이하', '전용면적 102㎡초과', '전용면적 102㎡초과', '전용면적 60㎡이하', '전용면적 102㎡초과', '전용면적 102㎡초과', '전용면적 60㎡이하', '전용면적 60㎡이하', '전용면적 102㎡초과', '전용면적 60㎡초과 85㎡이하', '전용면적 102㎡초과', '전용면적 60㎡초과 85㎡이하', '전용면적 102㎡초과', '전용면적 102㎡초과', '전용면적 102㎡초과', '전용면적 60㎡이하', '전용면적 102㎡초과', '전용면적 102㎡초과', '전용면적 102㎡초과', '전용면적 60㎡이하', '전용면적 102㎡초과', '전용면적 60㎡이하', '전용면적 60㎡초과 85㎡이하', '전용면적 102㎡초과', '전용면적 102㎡초과', '전용면적 102㎡초과', '전용면적 102㎡초과', '전용면적 102㎡초과', '전용면적 102㎡초과', '전용면적 102㎡초과', '전용면적 85㎡초과 102㎡이하', '전용면적 102㎡초과', '전용면적 102㎡초과']


[<p class="arrow"></p>, <p class="arrow"></p>, <p class="arrow"></p>, <p class="tag_blue">분양중</p>, <p>아파트</p>, <p>43,480 ~ 55,280만원</p>, <p>299 세대</p>, <p>2017.10 분양</p>, <p>2020.02 입주</p>, <p class="tag_blue">분양중</p>, <p>아파트</p>, <p>58,400 ~ 72,900만원</p>, <p>185 세대</p>, <p>2017.10 분양</p>, <p>2020.10 입주</p>, <p class="tag_blue">분양중</p>, <p>오피스텔</p>, <p>19,700만원</p>, <p>304 세대</p>, <p>2017.10 분양</p>, <p>2019.04 입주</p>, <p class="tag_blue">분양중</p>, <p>아파트</p>, <p>51,000 ~ 73,900만원</p>, <p>997 세대</p>, <p>2017.10 분양</p>, <p>2020.02 입주</p>, <p class="tag_blue">분양중</p>, <p>오피스텔</p>, <p>18,330 ~ 29,900만원</p>, <p>289 세대</p>, <p>2017.10 분양</p>, <p>2020.05 입주</p>, <p class="tag_blue">분양중</p>, <p>오피스텔</p>, <p>26,910 ~ 59,661만원</p>, <p>480 세대</p>, <p>2017.09 분양</p>, <p>2020.08 입주</p>, <p class="tag_blue">분양중</p>, <p>아파트</p>, <p>107,300 ~ 104,300만원</p>, <p>318 세대</p>, <p>2017.09 분양</p>, <p>2020.08 입주</p>, <p class="tag_blue">분양중</p>, <p>아파트</p>, <p>111,700 ~ 217,800만원</p>, <p>2,296 세대</p>, <p>2017.09 분양</p>, <p>2020.09 입주</p>, <p class="tag_blue">분양중</p>, <p>아파트</p>, <p>43,500 ~ 54,500만원</p>, <p>634 세대</p>, <p>2017.09 분양</p>, <p>2019.09 입주</p>, <p class="tag_blue">분양중</p>, <p>아파트</p>, <p>15,760 ~ 54,650만원</p>, <p>497 세대</p>, <p>2017.09 분양</p>, <p>2019.11 입주</p>, <p class="tag_blue">분양중</p>, <p>아파트</p>, <p>49,880 ~ 64,740만원</p>, <p>469 세대</p>, <p>2017.09 분양</p>, <p>2019.10 입주</p>, <p class="tag_blue">분양중</p>, <p>아파트</p>, <p>111,150 ~ 209,150만원</p>, <p>757 세대</p>, <p>2017.09 분양</p>, <p>2020.04 입주</p>, <p class="tag_blue">분양중</p>, <p>아파트</p>, <p>35,830 ~ 54,770만원</p>, <p>744 세대</p>, <p>2017.08 분양</p>, <p>2021.12 입주</p>, <p class="tag_blue">분양중</p>, <p>아파트</p>, <p>35,430 ~ 65,560천원</p>, <p>818 세대</p>, <p>2017.08 분양</p>, <p>2018.06 입주</p>, <p class="tag_blue">분양중</p>, <p>아파트</p>, <p>78,900 ~ 101,200만원</p>, <p>472 세대</p>, <p>2017.08 분양</p>, <p>2020.08 입주</p>, <p>아파트</p>, <p>아파트</p>, <p>아파트</p>, <p>아파트</p>, <p>아파트</p>, <p>제호 [ 분양정보닷컴 ]</p>, <p>고객센터</p>]


43,480 ~ 55,280만원
58,400 ~ 72,900만원
19,700만원
51,000 ~ 73,900만원
18,330 ~ 29,900만원
26,910 ~ 59,661만원
107,300 ~ 104,300만원
111,700 ~ 217,800만원
43,500 ~ 54,500만원
15,760 ~ 54,650만원
49,880 ~ 64,740만원
111,150 ~ 209,150만원
35,830 ~ 54,770만원
35,430 ~ 65,560천원
78,900 ~ 101,200만원


[1947700, 171960, 1385000, 85120, 1289000, 890000, 345000, 2277000, 350500, 240000, 316200, 661000, 826400, 350290, 681580, 828000, 356800, 289800, 497100, 399000, 1058280, 2500000, 731100, 648500, 723300, 149900, 585200, 552800, '43,480 ~ 55,280만원', '58,400 ~ 72,900만원', '19,700만원', '51,000 ~ 73,900만원', '18,330 ~ 29,900만원', '26,910 ~ 59,661만원', '107,300 ~ 104,300만원', '111,700 ~ 217,800만원', '43,500 ~ 54,500만원', '15,760 ~ 54,650만원', '49,880 ~ 64,740만원', '111,150 ~ 209,150만원', '35,830 ~ 54,770만원', '35,430 ~ 65,560천원', '78,900 ~ 101,200만원']


[1947700, 171960, 1385000, 85120, 1289000, 890000, 345000, 2277000, 350500, 240000, 316200, 661000, 826400, 350290, 681580, 828000, 356800, 289800, 497100, 399000, 1058280, 2500000, 731100, 648500, 723300, 149900, 585200, 552800, 729000, 197000, 739000, 299000, 596610, 1043000, 2178000, 545000, 546500, 647400, 2091500, 547700, 655600, 1012000, 685480]
[19095, 2866, 13578, 1001, 12637, 8725, 5750, 22323, 5841, 4000, 5270, 6480, 8101, 5838, 6682, 8117, 5946, 4830, 4873, 4694, 10375, 29411, 7167, 6357, 7091, 2498, 5737, 5419, 729000, 197000, 739000, 299000, 596610, 1043000, 2178000, 545000, 546500, 647400, 2091500, 547700, 655600, 1012000, 685480]
[<p class="arrow"></p>, <p class="arrow"></p>, <p class="arrow"></p>, <p class="tag_blue">분양중</p>, <p>아파트</p>, <p>43,480 ~ 55,280만원</p>, <p>299 세대</p>, <p>2017.10 분양</p>, <p>2020.02 입주</p>, <p class="tag_blue">분양중</p>, <p>아파트</p>, <p>58,400 ~ 72,900만원</p>, <p>185 세대</p>, <p>2017.10 분양</p>, <p>2020.10 입주</p>, <p class="tag_blue">분양중</p>, <p>오피스텔</p>, <p>19,700만원</p>, <p>304 세대</p>, <p>2017.10 분양</p>, <p>2019.04 입주</p>, <p class="tag_blue">분양중</p>, <p>아파트</p>, <p>51,000 ~ 73,900만원</p>, <p>997 세대</p>, <p>2017.10 분양</p>, <p>2020.02 입주</p>, <p class="tag_blue">분양중</p>, <p>오피스텔</p>, <p>18,330 ~ 29,900만원</p>, <p>289 세대</p>, <p>2017.10 분양</p>, <p>2020.05 입주</p>, <p class="tag_blue">분양중</p>, <p>오피스텔</p>, <p>26,910 ~ 59,661만원</p>, <p>480 세대</p>, <p>2017.09 분양</p>, <p>2020.08 입주</p>, <p class="tag_blue">분양중</p>, <p>아파트</p>, <p>107,300 ~ 104,300만원</p>, <p>318 세대</p>, <p>2017.09 분양</p>, <p>2020.08 입주</p>, <p class="tag_blue">분양중</p>, <p>아파트</p>, <p>111,700 ~ 217,800만원</p>, <p>2,296 세대</p>, <p>2017.09 분양</p>, <p>2020.09 입주</p>, <p class="tag_blue">분양중</p>, <p>아파트</p>, <p>43,500 ~ 54,500만원</p>, <p>634 세대</p>, <p>2017.09 분양</p>, <p>2019.09 입주</p>, <p class="tag_blue">분양중</p>, <p>아파트</p>, <p>15,760 ~ 54,650만원</p>, <p>497 세대</p>, <p>2017.09 분양</p>, <p>2019.11 입주</p>, <p class="tag_blue">분양중</p>, <p>아파트</p>, <p>49,880 ~ 64,740만원</p>, <p>469 세대</p>, <p>2017.09 분양</p>, <p>2019.10 입주</p>, <p class="tag_blue">분양중</p>, <p>아파트</p>, <p>111,150 ~ 209,150만원</p>, <p>757 세대</p>, <p>2017.09 분양</p>, <p>2020.04 입주</p>, <p class="tag_blue">분양중</p>, <p>아파트</p>, <p>35,830 ~ 54,770만원</p>, <p>744 세대</p>, <p>2017.08 분양</p>, <p>2021.12 입주</p>, <p class="tag_blue">분양중</p>, <p>아파트</p>, <p>35,430 ~ 65,560천원</p>, <p>818 세대</p>, <p>2017.08 분양</p>, <p>2018.06 입주</p>, <p class="tag_blue">분양중</p>, <p>아파트</p>, <p>78,900 ~ 101,200만원</p>, <p>472 세대</p>, <p>2017.08 분양</p>, <p>2020.08 입주</p>, <p>아파트</p>, <p>아파트</p>, <p>아파트</p>, <p>아파트</p>, <p>아파트</p>, <p>제호 [ 분양정보닷컴 ]</p>, <p>고객센터</p>]


2017.10 분양
2017.10 분양
2017.10 분양
2017.10 분양
2017.10 분양
2017.09 분양
2017.09 분양
2017.09 분양
2017.09 분양
2017.09 분양
2017.09 분양
2017.09 분양
2017.08 분양
2017.08 분양
2017.08 분양


['2019', '2019', '2019', '2019', '2019', '2019', '2018', '2018', '2018', '2018', '2018', '2018', '2018', '2018', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017.10 분양', '2017.10 분양', '2017.10 분양', '2017.10 분양', '2017.10 분양', '2017.09 분양', '2017.09 분양', '2017.09 분양', '2017.09 분양', '2017.09 분양', '2017.09 분양', '2017.09 분양', '2017.08 분양', '2017.08 분양', '2017.08 분양']


['2019', '2019', '2019', '2019', '2019', '2019', '2018', '2018', '2018', '2018', '2018', '2018', '2018', '2018', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017']

   지역명               규모구분     분양가격  평당분양가격    연도
0   서울        전용면적 102㎡초과  1947700   19095  2019
1   서울         전용면적 60㎡이하   171960    2866  2019
2   서울        전용면적 102㎡초과  1385000   13578  2019
3   서울   전용면적 60㎡초과 85㎡이하    85120    1001  2019
4   서울  전용면적 85㎡초과 102㎡이하  1289000   12637  2019
5   서울        전용면적 102㎡초과   890000    8725  2019
6   서울         전용면적 60㎡이하   345000    5750  2018
7   서울        전용면적 102㎡초과  2277000   22323  2018
8   서울         전용면적 60㎡이하   350500    5841  2018
9   서울         전용면적 60㎡이하   240000    4000  2018
10  서울         전용면적 60㎡이하   316200    5270  2018
11  서울        전용면적 102㎡초과   661000    6480  2018
12  서울        전용면적 102㎡초과   826400    8101  2018
13  서울         전용면적 60㎡이하   350290    5838  2018
14  서울        전용면적 102㎡초과   681580    6682  2017
15  서울        전용면적 102㎡초과   828000    8117  2017
16  서울         전용면적 60㎡이하   356800    5946  2017
17  서울         전용면적 60㎡이하   289800    4830  2017
18  서울        전용면적 102㎡초과   497100    4873  2017
19  서울   전용면적 60㎡초과 85㎡이하   399000    4694  2017
20  서울        전용면적 102㎡초과  1058280   10375  2017
21  서울   전용면적 60㎡초과 85㎡이하  2500000   29411  2017
22  서울        전용면적 102㎡초과   731100    7167  2017
23  서울        전용면적 102㎡초과   648500    6357  2017
24  서울        전용면적 102㎡초과   723300    7091  2017
25  서울         전용면적 60㎡이하   149900    2498  2017
26  서울        전용면적 102㎡초과   585200    5737  2017
27  서울        전용면적 102㎡초과   552800    5419  2017
28  서울        전용면적 102㎡초과   729000    7147  2017
29  서울         전용면적 60㎡이하   197000    3283  2017
30  서울        전용면적 102㎡초과   739000    7245  2017
31  서울         전용면적 60㎡이하   299000    4983  2017
32  서울   전용면적 60㎡초과 85㎡이하   596610    9943  2017
33  서울        전용면적 102㎡초과  1043000   10225  2017
34  서울        전용면적 102㎡초과  2178000   21352  2017
35  서울        전용면적 102㎡초과   545000    5343  2017
36  서울        전용면적 102㎡초과   546500    5357  2017
37  서울        전용면적 102㎡초과   647400    6347  2017
38  서울        전용면적 102㎡초과  2091500   20504  2017
39  서울        전용면적 102㎡초과   547700    5369  2017
40  서울  전용면적 85㎡초과 102㎡이하   655600    7712  2017
41  서울        전용면적 102㎡초과  1012000    9921  2017
42  서울        전용면적 102㎡초과   685480    6720  2017

In [45]:
# [4 page]
def get_html(url) :
    html = ""
    resp = requests.get(url)
    if resp.status_code == 200 :
        html = resp.text
    return html
html = get_html('http://www.boonyang24.com/?sub=boonyang_info/info_list&do1=&si1=&boonryu01=&boonryu02=&page=4&keyword=&tp=&cate=&area_code=&work_year=&hyun_cate=')
soup = BeautifulSoup(html, 'html.parser')
boonyang = soup.find("div",{"class":"list_type_boonyang"})
#----------------------------------------------------------------------

#----------------------------------------------------------------------

Citycell = {}

#지역에 대한 리스트

w_city3 = soup.find_all('td', {'class':'subject'})
#다 서울이기 때문에 모든 리스트의 요소를 '서울'로 간단하게 바꿔줌. 

for i in range(0, 15):   #0~14
    w_city3[i]
    print(w_city3[i].text)
print('\n')

for i in range(0, 15):
    w_city3[i] = "서울"
for i in range(0, 15):
    w_city_l.append(w_city3[i])
    
print(w_city_l)
print('\n')

Citycell['지역명'] = w_city_l
sd = pd.DataFrame(Citycell)
sd = sd[['지역명']]

#----------------------------------------------------------------------
#규모에 대한 내용.
# "전용면적 60㎡이하"  ,   "전용면적 60㎡초과 85㎡이하"
# "전용면적 85㎡초과 102㎡이하",  "전용면적 102㎡초과"
w_size3 = soup.find_all('b')
for i in range(0, 15):
    del w_size3[i]
w_size3[0] = "전용면적 102㎡초과"
w_size3[1] = "전용면적 102㎡초과"
w_size3[2] = "전용면적 102㎡초과"
w_size3[3] = "전용면적 60㎡이하"
w_size3[4] = "전용면적 102㎡초과"
w_size3[5] = "전용면적 102㎡초과"
w_size3[6] = "전용면적 60㎡이하"
w_size3[7] = "전용면적 60㎡이하"
w_size3[8] = "전용면적 102㎡초과"
w_size3[9] = "전용면적 102㎡초과"
w_size3[10] = "전용면적 60㎡이하"
w_size3[11] = "전용면적 102㎡초과"
w_size3[12] = "전용면적 60㎡이하"
w_size3[13] = "전용면적 102㎡초과"
w_size3[14] = "전용면적 102㎡초과"
print(w_size3)

for i in range(0, 15):
    w_size_l.append(w_size3[i])
print(w_size_l)

Citycell['지역명'] = w_city_l
Citycell['규모구분'] = w_size_l
sd = pd.DataFrame(Citycell)

sd = sd[['지역명', '규모구분']]

#----------------------------------------------------------------------
print('\n')
w_price3 = soup.find_all('p')
print(w_price3)               #6번째 주기로 가격정보가 나오는걸 알 수 있다.
                            #'미정'처리된 두 지역은 빼고 생각하였다.
print('\n')

for i in range(1,16):
    print(w_price3[6*i-1].text)   
    w_price_l.extend(w_price3[6*i-1])   #등차수열 이용.
print('\n')
print(w_price_l)
    
Citycell['지역명'] = w_city_l
Citycell['규모구분'] = w_size_l
Citycell['분양가격'] = w_price_l
sd = pd.DataFrame(Citycell)

sd = sd[['지역명', '규모구분','분양가격']]

#----------------------------------------------------------------------
#크롤링한 사이트는 단위가 '만 원'이다.
#본래 데이터분석을 한 자료의 단위는 '천 원'이므로 끝에 0을 더 붙여서 할당하였다.
w_price_l[43] = 685480
w_price_l[44] = 899000
w_price_l[45] = 6254100
w_price_l[46] = 110000
w_price_l[47] = 858000
w_price_l[48] = 638000
w_price_l[49] = 282000
w_price_l[50] = 205000
w_price_l[51] = 770000
w_price_l[52] = 535500
w_price_l[53] = 275000
w_price_l[54] = 639950
w_price_l[55] = 700000
w_price_l[56] = 939000
w_price_l[57] = 1991000
print('\n')
print(w_price_l)
#pandas 처리
sd = pd.DataFrame(Citycell)
sd = sd[['지역명', '규모구분','분양가격']]

#----------------------------------------------------------------------
#평당분양가격
sd['분양가격'] = pd.to_numeric(w_price_l, errors = 'coerce')

for i in range(43, 58):
    w_square.append(w_price_l[i])
print(w_square)
w_square[43] = int(685480/102)
w_square[44] = int(899000/102)
w_square[45] = int(6254100/102)
w_square[46] = int(110000/60)
w_square[47] = int(858000/102)
w_square[48] = int(638000/102)
w_square[49] = int(282000/60)
w_square[50] = int(205000/60)
w_square[51] = int(770000/102)
w_square[52] = int(535500/102)
w_square[53] = int(275000/60)
w_square[54] = int(639950/102)
w_square[55] = int(700000/60)
w_square[56] = int(939000/102)
w_square[57] = int(1991000/102)

Citycell['평당분양가격'] = w_square
sd = pd.DataFrame(Citycell)
sd = sd[['지역명', '규모구분','분양가격','평당분양가격']]

#----------------------------------------------------------------------

#연도에 대한 리스트 필요.
w_year3 = soup.find_all('p')
print(w_year3)
print('\n')
#7, 13, 19, 25 a+(n-1)d
#7+(i-1)*6        // 등차수열 이용.
for i in range(1,16):
    print(w_year3[7+(i-1)*6].text)    
    w_year_l.extend(w_year3[7+(i-1)*6])
    
print('\n')
print(w_year_l)

for i in range(43,58):
    w_year_l[i] = '2017'
print('\n')
print(w_year_l)

#pandas 처리
Citycell['지역명'] = w_city_l
Citycell['규모구분'] = w_size_l
Citycell['가격'] = w_price_l
Citycell['연도'] = w_year_l

sd = pd.DataFrame(Citycell)
sd = sd[['지역명', '규모구분','분양가격','평당분양가격', '연도']]
sd

이수역리가 서울특별시 동작구 사당동 1157
DMC에코자이 서울특별시 서대문구 남가좌동 242-14
아크로서울포레스트 서울특별시 성동구 성수동1가 685-700 (
한일노벨리아시티 서울특별시 성북구 장위동 8-2외 6필지
신길센트럴자이 서울특별시 영등포구 신길동 337-246
관악파크뷰 서울 관악구 봉천동 66번지 일대
M펠리체(빌라) 서울시 강서구 화곡동 424-80
위드하우스(빌라) 서울시 은평구 갈현동 489-9
서울항동지구중흥S-클래스 서울특별시 구로구 항동 100-5 (항동지
상계역센트럴푸르지오 서울특별시 노원구 상계동 85-33
상봉베스트원 서울특별시 중랑구 상봉동 101-18
오금공공주택지구2단지(공공분양) 서울특별시 송파구 오금동 99
H-House대림뉴스테이 서울특별시 영등포구 대림동 994-1
고덕센트럴IPARK 서울특별시 강동구 상일동 131번지 일
용산센트럴파크해링턴스퀘어 서울특별시 용산구 한강로3가 63-70번


['서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울']


['전용면적 102㎡초과', '전용면적 102㎡초과', '전용면적 102㎡초과', '전용면적 60㎡이하', '전용면적 102㎡초과', '전용면적 102㎡초과', '전용면적 60㎡이하', '전용면적 60㎡이하', '전용면적 102㎡초과', '전용면적 102㎡초과', '전용면적 60㎡이하', '전용면적 102㎡초과', '전용면적 60㎡이하', '전용면적 102㎡초과', '전용면적 102㎡초과']
['전용면적 102㎡초과', '전용면적 60㎡이하', '전용면적 102㎡초과', '전용면적 60㎡초과 85㎡이하', '전용면적 85㎡초과 102㎡이하', '전용면적 102㎡초과', '전용면적 60㎡이하', '전용면적 102㎡초과', '전용면적 60㎡이하', '전용면적 60㎡이하', '전용면적 60㎡이하', '전용면적 102㎡초과', '전용면적 102㎡초과', '전용면적 60㎡이하', '전용면적 102㎡초과', '전용면적 102㎡초과', '전용면적 60㎡이하', '전용면적 60㎡이하', '전용면적 102㎡초과', '전용면적 60㎡초과 85㎡이하', '전용면적 102㎡초과', '전용면적 60㎡초과 85㎡이하', '전용면적 102㎡초과', '전용면적 102㎡초과', '전용면적 102㎡초과', '전용면적 60㎡이하', '전용면적 102㎡초과', '전용면적 102㎡초과', '전용면적 102㎡초과', '전용면적 60㎡이하', '전용면적 102㎡초과', '전용면적 60㎡이하', '전용면적 60㎡초과 85㎡이하', '전용면적 102㎡초과', '전용면적 102㎡초과', '전용면적 102㎡초과', '전용면적 102㎡초과', '전용면적 102㎡초과', '전용면적 102㎡초과', '전용면적 102㎡초과', '전용면적 85㎡초과 102㎡이하', '전용면적 102㎡초과', '전용면적 102㎡초과', '전용면적 102㎡초과', '전용면적 102㎡초과', '전용면적 102㎡초과', '전용면적 60㎡이하', '전용면적 102㎡초과', '전용면적 102㎡초과', '전용면적 60㎡이하', '전용면적 60㎡이하', '전용면적 102㎡초과', '전용면적 102㎡초과', '전용면적 60㎡이하', '전용면적 102㎡초과', '전용면적 60㎡이하', '전용면적 102㎡초과', '전용면적 102㎡초과']


[<p class="arrow"></p>, <p class="arrow"></p>, <p class="arrow"></p>, <p class="tag_blue">분양중</p>, <p>아파트</p>, <p>67,755 ~ 68,548만원</p>, <p>452 세대</p>, <p>2017.08 분양</p>, <p>2017.09 입주</p>, <p class="tag_blue">분양중</p>, <p>아파트</p>, <p>49,800 ~ 89,900만원</p>, <p>1,047 세대</p>, <p>2017.08 분양</p>, <p>2019.12 입주</p>, <p class="tag_blue">분양중</p>, <p>아파트</p>, <p>169,800 ~ 625,410만원</p>, <p>280 세대</p>, <p>2017.08 분양</p>, <p>2020.10 입주</p>, <p class="tag_blue">분양중</p>, <p>오피스텔</p>, <p>11,000만원</p>, <p>539 세대</p>, <p>2017.07 분양</p>, <p>2019.07 입주</p>, <p class="tag_blue">분양중</p>, <p>아파트</p>, <p>39,850 ~ 85,800만원</p>, <p>1,008 세대</p>, <p>2017.07 분양</p>, <p>2020.02 입주</p>, <p class="tag_blue">분양중</p>, <p>아파트</p>, <p>37,899 ~ 63,800만원</p>, <p>980 세대</p>, <p>2017.07 분양</p>, <p>2021.12 입주</p>, <p class="tag_blue">분양중</p>, <p>기타</p>, <p>19,200 ~ 28,200만원</p>, <p>16 세대</p>, <p>2017.07 분양</p>, <p>2017.07 입주</p>, <p class="tag_blue">분양중</p>, <p>기타</p>, <p>19,500 ~ 20,500만원</p>, <p>15 세대</p>, <p>2017.07 분양</p>, <p>2017.07 입주</p>, <p class="tag_blue">분양중</p>, <p>아파트</p>, <p>49,700 ~ 77,000만원</p>, <p>419 세대</p>, <p>2017.07 분양</p>, <p>2019.12 입주</p>, <p class="tag_blue">분양중</p>, <p>아파트</p>, <p>34,180 ~ 53,550만원</p>, <p>810 세대</p>, <p>2017.07 분양</p>, <p>2020.01 입주</p>, <p class="tag_blue">분양중</p>, <p>아파트</p>, <p>14,500 ~ 27,500만원</p>, <p>114 세대</p>, <p>2017.07 분양</p>, <p>2019.04 입주</p>, <p class="tag_blue">분양중</p>, <p>아파트</p>, <p>49,286 ~ 63,995만원</p>, <p>818 세대</p>, <p>2017.07 분양</p>, <p>2018.06 입주</p>, <p class="tag_blue">분양중</p>, <p>아파트</p>, <p>10,000 ~ 70,000천원</p>, <p>291 세대</p>, <p>2017.07 분양</p>, <p>2017.08 입주</p>, <p class="tag_blue">분양중</p>, <p>아파트</p>, <p>60,900 ~ 93,900만원</p>, <p>1,745 세대</p>, <p>2017.06 분양</p>, <p>2020.02 입주</p>, <p class="tag_blue">분양중</p>, <p>아파트</p>, <p>154,600 ~ 199,100만원</p>, <p>1,140 세대</p>, <p>2017.06 분양</p>, <p>2020.08 입주</p>, <p>아파트</p>, <p>아파트</p>, <p>아파트</p>, <p>아파트</p>, <p>아파트</p>, <p>제호 [ 분양정보닷컴 ]</p>, <p>고객센터</p>]


67,755 ~ 68,548만원
49,800 ~ 89,900만원
169,800 ~ 625,410만원
11,000만원
39,850 ~ 85,800만원
37,899 ~ 63,800만원
19,200 ~ 28,200만원
19,500 ~ 20,500만원
49,700 ~ 77,000만원
34,180 ~ 53,550만원
14,500 ~ 27,500만원
49,286 ~ 63,995만원
10,000 ~ 70,000천원
60,900 ~ 93,900만원
154,600 ~ 199,100만원


[1947700, 171960, 1385000, 85120, 1289000, 890000, 345000, 2277000, 350500, 240000, 316200, 661000, 826400, 350290, 681580, 828000, 356800, 289800, 497100, 399000, 1058280, 2500000, 731100, 648500, 723300, 149900, 585200, 552800, 729000, 197000, 739000, 299000, 596610, 1043000, 2178000, 545000, 546500, 647400, 2091500, 547700, 655600, 1012000, 685480, '67,755 ~ 68,548만원', '49,800 ~ 89,900만원', '169,800 ~ 625,410만원', '11,000만원', '39,850 ~ 85,800만원', '37,899 ~ 63,800만원', '19,200 ~ 28,200만원', '19,500 ~ 20,500만원', '49,700 ~ 77,000만원', '34,180 ~ 53,550만원', '14,500 ~ 27,500만원', '49,286 ~ 63,995만원', '10,000 ~ 70,000천원', '60,900 ~ 93,900만원', '154,600 ~ 199,100만원']


[1947700, 171960, 1385000, 85120, 1289000, 890000, 345000, 2277000, 350500, 240000, 316200, 661000, 826400, 350290, 681580, 828000, 356800, 289800, 497100, 399000, 1058280, 2500000, 731100, 648500, 723300, 149900, 585200, 552800, 729000, 197000, 739000, 299000, 596610, 1043000, 2178000, 545000, 546500, 647400, 2091500, 547700, 655600, 1012000, 685480, 685480, 899000, 6254100, 110000, 858000, 638000, 282000, 205000, 770000, 535500, 275000, 639950, 700000, 939000, 1991000]
[19095, 2866, 13578, 1001, 12637, 8725, 5750, 22323, 5841, 4000, 5270, 6480, 8101, 5838, 6682, 8117, 5946, 4830, 4873, 4694, 10375, 29411, 7167, 6357, 7091, 2498, 5737, 5419, 7147, 3283, 7245, 4983, 9943, 10225, 21352, 5343, 5357, 6347, 20504, 5369, 7712, 9921, 6720, 685480, 899000, 6254100, 110000, 858000, 638000, 282000, 205000, 770000, 535500, 275000, 639950, 700000, 939000, 1991000]
[<p class="arrow"></p>, <p class="arrow"></p>, <p class="arrow"></p>, <p class="tag_blue">분양중</p>, <p>아파트</p>, <p>67,755 ~ 68,548만원</p>, <p>452 세대</p>, <p>2017.08 분양</p>, <p>2017.09 입주</p>, <p class="tag_blue">분양중</p>, <p>아파트</p>, <p>49,800 ~ 89,900만원</p>, <p>1,047 세대</p>, <p>2017.08 분양</p>, <p>2019.12 입주</p>, <p class="tag_blue">분양중</p>, <p>아파트</p>, <p>169,800 ~ 625,410만원</p>, <p>280 세대</p>, <p>2017.08 분양</p>, <p>2020.10 입주</p>, <p class="tag_blue">분양중</p>, <p>오피스텔</p>, <p>11,000만원</p>, <p>539 세대</p>, <p>2017.07 분양</p>, <p>2019.07 입주</p>, <p class="tag_blue">분양중</p>, <p>아파트</p>, <p>39,850 ~ 85,800만원</p>, <p>1,008 세대</p>, <p>2017.07 분양</p>, <p>2020.02 입주</p>, <p class="tag_blue">분양중</p>, <p>아파트</p>, <p>37,899 ~ 63,800만원</p>, <p>980 세대</p>, <p>2017.07 분양</p>, <p>2021.12 입주</p>, <p class="tag_blue">분양중</p>, <p>기타</p>, <p>19,200 ~ 28,200만원</p>, <p>16 세대</p>, <p>2017.07 분양</p>, <p>2017.07 입주</p>, <p class="tag_blue">분양중</p>, <p>기타</p>, <p>19,500 ~ 20,500만원</p>, <p>15 세대</p>, <p>2017.07 분양</p>, <p>2017.07 입주</p>, <p class="tag_blue">분양중</p>, <p>아파트</p>, <p>49,700 ~ 77,000만원</p>, <p>419 세대</p>, <p>2017.07 분양</p>, <p>2019.12 입주</p>, <p class="tag_blue">분양중</p>, <p>아파트</p>, <p>34,180 ~ 53,550만원</p>, <p>810 세대</p>, <p>2017.07 분양</p>, <p>2020.01 입주</p>, <p class="tag_blue">분양중</p>, <p>아파트</p>, <p>14,500 ~ 27,500만원</p>, <p>114 세대</p>, <p>2017.07 분양</p>, <p>2019.04 입주</p>, <p class="tag_blue">분양중</p>, <p>아파트</p>, <p>49,286 ~ 63,995만원</p>, <p>818 세대</p>, <p>2017.07 분양</p>, <p>2018.06 입주</p>, <p class="tag_blue">분양중</p>, <p>아파트</p>, <p>10,000 ~ 70,000천원</p>, <p>291 세대</p>, <p>2017.07 분양</p>, <p>2017.08 입주</p>, <p class="tag_blue">분양중</p>, <p>아파트</p>, <p>60,900 ~ 93,900만원</p>, <p>1,745 세대</p>, <p>2017.06 분양</p>, <p>2020.02 입주</p>, <p class="tag_blue">분양중</p>, <p>아파트</p>, <p>154,600 ~ 199,100만원</p>, <p>1,140 세대</p>, <p>2017.06 분양</p>, <p>2020.08 입주</p>, <p>아파트</p>, <p>아파트</p>, <p>아파트</p>, <p>아파트</p>, <p>아파트</p>, <p>제호 [ 분양정보닷컴 ]</p>, <p>고객센터</p>]


2017.08 분양
2017.08 분양
2017.08 분양
2017.07 분양
2017.07 분양
2017.07 분양
2017.07 분양
2017.07 분양
2017.07 분양
2017.07 분양
2017.07 분양
2017.07 분양
2017.07 분양
2017.06 분양
2017.06 분양


['2019', '2019', '2019', '2019', '2019', '2019', '2018', '2018', '2018', '2018', '2018', '2018', '2018', '2018', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017.08 분양', '2017.08 분양', '2017.08 분양', '2017.07 분양', '2017.07 분양', '2017.07 분양', '2017.07 분양', '2017.07 분양', '2017.07 분양', '2017.07 분양', '2017.07 분양', '2017.07 분양', '2017.07 분양', '2017.06 분양', '2017.06 분양']


['2019', '2019', '2019', '2019', '2019', '2019', '2018', '2018', '2018', '2018', '2018', '2018', '2018', '2018', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017']

   지역명               규모구분     분양가격  평당분양가격    연도
0   서울        전용면적 102㎡초과  1947700   19095  2019
1   서울         전용면적 60㎡이하   171960    2866  2019
2   서울        전용면적 102㎡초과  1385000   13578  2019
3   서울   전용면적 60㎡초과 85㎡이하    85120    1001  2019
4   서울  전용면적 85㎡초과 102㎡이하  1289000   12637  2019
5   서울        전용면적 102㎡초과   890000    8725  2019
6   서울         전용면적 60㎡이하   345000    5750  2018
7   서울        전용면적 102㎡초과  2277000   22323  2018
8   서울         전용면적 60㎡이하   350500    5841  2018
9   서울         전용면적 60㎡이하   240000    4000  2018
10  서울         전용면적 60㎡이하   316200    5270  2018
11  서울        전용면적 102㎡초과   661000    6480  2018
12  서울        전용면적 102㎡초과   826400    8101  2018
13  서울         전용면적 60㎡이하   350290    5838  2018
14  서울        전용면적 102㎡초과   681580    6682  2017
15  서울        전용면적 102㎡초과   828000    8117  2017
16  서울         전용면적 60㎡이하   356800    5946  2017
17  서울         전용면적 60㎡이하   289800    4830  2017
18  서울        전용면적 102㎡초과   497100    4873  2017
19  서울   전용면적 60㎡초과 85㎡이하   399000    4694  2017
20  서울        전용면적 102㎡초과  1058280   10375  2017
21  서울   전용면적 60㎡초과 85㎡이하  2500000   29411  2017
22  서울        전용면적 102㎡초과   731100    7167  2017
23  서울        전용면적 102㎡초과   648500    6357  2017
24  서울        전용면적 102㎡초과   723300    7091  2017
25  서울         전용면적 60㎡이하   149900    2498  2017
26  서울        전용면적 102㎡초과   585200    5737  2017
27  서울        전용면적 102㎡초과   552800    5419  2017
28  서울        전용면적 102㎡초과   729000    7147  2017
29  서울         전용면적 60㎡이하   197000    3283  2017
30  서울        전용면적 102㎡초과   739000    7245  2017
31  서울         전용면적 60㎡이하   299000    4983  2017
32  서울   전용면적 60㎡초과 85㎡이하   596610    9943  2017
33  서울        전용면적 102㎡초과  1043000   10225  2017
34  서울        전용면적 102㎡초과  2178000   21352  2017
35  서울        전용면적 102㎡초과   545000    5343  2017
36  서울        전용면적 102㎡초과   546500    5357  2017
37  서울        전용면적 102㎡초과   647400    6347  2017
38  서울        전용면적 102㎡초과  2091500   20504  2017
39  서울        전용면적 102㎡초과   547700    5369  2017
40  서울  전용면적 85㎡초과 102㎡이하   655600    7712  2017
41  서울        전용면적 102㎡초과  1012000    9921  2017
42  서울        전용면적 102㎡초과   685480    6720  2017
43  서울        전용면적 102㎡초과   685480    6720  2017
44  서울        전용면적 102㎡초과   899000    8813  2017
45  서울        전용면적 102㎡초과  6254100   61314  2017
46  서울         전용면적 60㎡이하   110000    1833  2017
47  서울        전용면적 102㎡초과   858000    8411  2017
48  서울        전용면적 102㎡초과   638000    6254  2017
49  서울         전용면적 60㎡이하   282000    4700  2017
50  서울         전용면적 60㎡이하   205000    3416  2017
51  서울        전용면적 102㎡초과   770000    7549  2017
52  서울        전용면적 102㎡초과   535500    5250  2017
53  서울         전용면적 60㎡이하   275000    4583  2017
54  서울        전용면적 102㎡초과   639950    6274  2017
55  서울         전용면적 60㎡이하   700000   11666  2017
56  서울        전용면적 102㎡초과   939000    9205  2017
57  서울        전용면적 102㎡초과  1991000   19519  2017

In [46]:
#[5 page]
def get_html(url) :
    html = ""
    resp = requests.get(url)
    if resp.status_code == 200 :
        html = resp.text
    return html
html = get_html('http://www.boonyang24.com/?sub=boonyang_info/info_list&do1=&si1=&boonryu01=&boonryu02=&page=5&keyword=&tp=&cate=&area_code=&work_year=&hyun_cate=')
soup = BeautifulSoup(html, 'html.parser')
boonyang = soup.find("div",{"class":"list_type_boonyang"})
#----------------------------------------------------------------------

#지역에 대한 리스트
Citycell = {}

w_city4 = soup.find_all('td', {'class':'subject'})
#다 서울이기 때문에 모든 리스트의 요소를 '서울'로 간단하게 바꿔줌. 

for i in range(0, 15):   #0~14
    w_city4[i]
    print(w_city4[i].text)
print('\n')

for i in range(0, 15):
    w_city4[i] = "서울"
for i in range(0, 15):
    w_city_l.append(w_city4[i])
    
print(w_city_l)
print('\n')

Citycell['지역명'] = w_city_l
sd = pd.DataFrame(Citycell)
sd = sd[['지역명']]

#----------------------------------------------------------------------
#규모에 대한 내용.
# "전용면적 60㎡이하"  ,   "전용면적 60㎡초과 85㎡이하"
# "전용면적 85㎡초과 102㎡이하",  "전용면적 102㎡초과"
w_size4 = soup.find_all('b')
for i in range(0, 13):  #28개 
    del w_size4[i]
w_size4[0] = "전용면적 102㎡초과"
w_size4[1] = "전용면적 102㎡초과"
w_size4[2] = "전용면적 60㎡초과 85㎡이하"
w_size4[3] = "전용면적 60㎡초과 85㎡이하"
w_size4[4] = "전용면적 102㎡초과"
w_size4[5] = "전용면적 60㎡이하"
w_size4[6] = "전용면적 60㎡이하"
w_size4[7] = "전용면적 102㎡초과"
w_size4[8] = "전용면적 60㎡초과 85㎡이하"
w_size4[9] = "전용면적 60㎡이하"
w_size4[10] = "전용면적 60㎡초과 85㎡이하"
w_size4[11] = "전용면적 102㎡초과"
w_size4[12] = "전용면적 60㎡이하"
w_size4[13] = "전용면적 102㎡초과"
w_size4[14] = "전용면적 60㎡이하"
print(w_size4)

for i in range(0, 15):
    w_size_l.append(w_size4[i])
print(w_size_l)

Citycell['지역명'] = w_city_l
Citycell['규모구분'] = w_size_l
sd = pd.DataFrame(Citycell)
sd = sd[['지역명', '규모구분']]

#----------------------------------------------------------------------
print('\n')
w_price4 = soup.find_all('p')
print(w_price4)               #6번째 주기로 가격정보가 나오는걸 알 수 있다.
                            #'미정'처리된 두 지역은 빼고 생각하였다.
print('\n')
for i in range(1,16):
    print(w_price4[6*i-1].text)   
    w_price_l.extend(w_price4[6*i-1])   #등차수열 이용.
print('\n')
print(w_price_l)
    
Citycell['지역명'] = w_city_l
Citycell['규모구분'] = w_size_l
Citycell['분양가격'] = w_price_l
sd = pd.DataFrame(Citycell)
sd = sd[['지역명', '규모구분','분양가격']]

#----------------------------------------------------------------------
#크롤링한 사이트는 단위가 '만 원'이다.
#본래 데이터분석을 한 자료의 단위는 '천 원'이므로 끝에 0을 더 붙여서 할당하였다.
w_price_l[58] = 576000
w_price_l[59] = 713000
w_price_l[60] = 662000
w_price_l[61] = 347000
w_price_l[62] = 576000
w_price_l[63] = 165000
w_price_l[64] = 332000
w_price_l[65] = 1001000
w_price_l[66] = 415000
w_price_l[67] = 376000
w_price_l[68] = 318000
w_price_l[69] = 1095000
w_price_l[70] = 217570
w_price_l[71] = 4390000
w_price_l[72] = 497000

print('\n')
print(w_price_l)
#pandas 처리
sd = pd.DataFrame(Citycell)
sd = sd[['지역명', '규모구분','분양가격']]

#----------------------------------------------------------------------
#평당분양가격
sd['분양가격'] = pd.to_numeric(w_price_l, errors = 'coerce')

for i in range(58, 73):
    w_square.append(w_price_l[i])
print(w_square)

w_square[58] = int(576000/102)
w_square[59] = int(713000/102)
w_square[60] = int(662000/85)
w_square[61] = int(347000/85)
w_square[62] = int(576000/102)
w_square[63] = int(165000/60)
w_square[64] = int(332000/60)
w_square[65] = int(1001000/102)
w_square[66] = int(415000/85)
w_square[67] = int(376000/60)
w_square[68] = int(318000/85)
w_square[69] = int(1095000/102)
w_square[70] = int(217570/60)
w_square[71] = int(4390000/102)
w_square[72] = int(497000/60)
Citycell['평당분양가격'] = w_square
sd = pd.DataFrame(Citycell)
sd = sd[['지역명', '규모구분','분양가격','평당분양가격']]

#----------------------------------------------------------------------

#연도에 대한 리스트 필요.
w_year4 = soup.find_all('p')
print(w_year4)
print('\n')
#7, 13, 19, 25 a+(n-1)d
#7+(i-1)*6        // 등차수열 이용.
for i in range(1,16):
    print(w_year4[7+(i-1)*6].text)    
    w_year_l.extend(w_year4[7+(i-1)*6])
    
print('\n')
print(w_year_l)

for i in range(58,73):
    w_year_l[i] = '2017'
print('\n')
print(w_year_l)

#pandas 처리
Citycell['지역명'] = w_city_l
Citycell['규모구분'] = w_size_l
Citycell['가격'] = w_price_l
Citycell['연도'] = w_year_l

sd = pd.DataFrame(Citycell)
sd = sd[['지역명', '규모구분','분양가격','평당분양가격', '연도']]
sd

인덕IPARK 서울특별시 노원구 월계동 633-31번지
DMC롯데캐슬더퍼스트 서울시 은평구 수색동 361-10번지 일원
고덕센트럴푸르지오 서울특별시 강동구 고덕동 210-1
청명에버아트3(빌라) 서울특별시 동대문구 장안동 372-8
신정뉴타운아이파크위브 서울특별시 양천구 신월6동 551-1 일대
공덕솔리스타(오피스텔) 서울특별시 마포구 공덕동 30-19
공덕솔리스타(도·생) 서울특별시 마포구 공덕동 30-19
고덕롯데캐슬베네루체 서울특별시 강동구 상일동 187
파랑새 서울 광진구 자양동 683-6
여의휴젠느 서울특별시 영등포구 영등포동7가 94-9
세정앙떼빌 서울 은평구 불광천길 388-22
보라매SK뷰 서울 영등포구 신길동 1583-1
강남헤븐리치 서울 서초구 서초동 1339
목동 슬로우스퀘어 서울시 양천구 목동 406-28
비버리하임 서울시 서초구 양재동 5-9


['서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울']


['전용면적 102㎡초과', '전용면적 102㎡초과', '전용면적 60㎡초과 85㎡이하', '전용면적 60㎡초과 85㎡이하', '전용면적 102㎡초과', '전용면적 60㎡이하', '전용면적 60㎡이하', '전용면적 102㎡초과', '전용면적 60㎡초과 85㎡이하', '전용면적 60㎡이하', '전용면적 60㎡초과 85㎡이하', '전용면적 102㎡초과', '전용면적 60㎡이하', '전용면적 102㎡초과', '전용면적 60㎡이하']
['전용면적 102㎡초과', '전용면적 60㎡이하', '전용면적 102㎡초과', '전용면적 60㎡초과 85㎡이하', '전용면적 85㎡초과 102㎡이하', '전용면적 102㎡초과', '전용면적 60㎡이하', '전용면적 102㎡초과', '전용면적 60㎡이하', '전용면적 60㎡이하', '전용면적 60㎡이하', '전용면적 102㎡초과', '전용면적 102㎡초과', '전용면적 60㎡이하', '전용면적 102㎡초과', '전용면적 102㎡초과', '전용면적 60㎡이하', '전용면적 60㎡이하', '전용면적 102㎡초과', '전용면적 60㎡초과 85㎡이하', '전용면적 102㎡초과', '전용면적 60㎡초과 85㎡이하', '전용면적 102㎡초과', '전용면적 102㎡초과', '전용면적 102㎡초과', '전용면적 60㎡이하', '전용면적 102㎡초과', '전용면적 102㎡초과', '전용면적 102㎡초과', '전용면적 60㎡이하', '전용면적 102㎡초과', '전용면적 60㎡이하', '전용면적 60㎡초과 85㎡이하', '전용면적 102㎡초과', '전용면적 102㎡초과', '전용면적 102㎡초과', '전용면적 102㎡초과', '전용면적 102㎡초과', '전용면적 102㎡초과', '전용면적 102㎡초과', '전용면적 85㎡초과 102㎡이하', '전용면적 102㎡초과', '전용면적 102㎡초과', '전용면적 102㎡초과', '전용면적 102㎡초과', '전용면적 102㎡초과', '전용면적 60㎡이하', '전용면적 102㎡초과', '전용면적 102㎡초과', '전용면적 60㎡이하', '전용면적 60㎡이하', '전용면적 102㎡초과', '전용면적 102㎡초과', '전용면적 60㎡이하', '전용면적 102㎡초과', '전용면적 60㎡이하', '전용면적 102㎡초과', '전용면적 102㎡초과', '전용면적 102㎡초과', '전용면적 102㎡초과', '전용면적 60㎡초과 85㎡이하', '전용면적 60㎡초과 85㎡이하', '전용면적 102㎡초과', '전용면적 60㎡이하', '전용면적 60㎡이하', '전용면적 102㎡초과', '전용면적 60㎡초과 85㎡이하', '전용면적 60㎡이하', '전용면적 60㎡초과 85㎡이하', '전용면적 102㎡초과', '전용면적 60㎡이하', '전용면적 102㎡초과', '전용면적 60㎡이하']


[<p class="arrow"></p>, <p class="arrow"></p>, <p class="arrow"></p>, <p class="tag_blue">분양중</p>, <p>아파트</p>, <p>43,600 ~ 57,600만원</p>, <p>859 세대</p>, <p>2017.06 분양</p>, <p>2019.11 입주</p>, <p class="tag_blue">분양중</p>, <p>아파트</p>, <p>31,800 ~ 71,300만원</p>, <p>1,192 세대</p>, <p>2017.06 분양</p>, <p>2020.06 입주</p>, <p class="tag_blue">분양중</p>, <p>아파트</p>, <p>35,500 ~ 66,200만원</p>, <p>656 세대</p>, <p>2017.06 분양</p>, <p>2020.09 입주</p>, <p class="tag_blue">분양중</p>, <p>기타</p>, <p>34,700만원</p>, <p>34 세대</p>, <p>2017.06 분양</p>, <p>2017.07 입주</p>, <p class="tag_blue">분양중</p>, <p>아파트</p>, <p>40,800 ~ 57,600만원</p>, <p>3,045 세대</p>, <p>2017.06 분양</p>, <p>2020.03 입주</p>, <p class="tag_blue">분양중</p>, <p>오피스텔</p>, <p>15,900 ~ 16,500만원</p>, <p>154 세대</p>, <p>2017.06 분양</p>, <p>2017.10 입주</p>, <p class="tag_blue">분양중</p>, <p>도·생</p>, <p>16,400 ~ 33,200만원</p>, <p>154 세대</p>, <p>2017.06 분양</p>, <p>2018.10 입주</p>, <p class="tag_blue">분양중</p>, <p>아파트</p>, <p>56,200 ~ 100,100만원</p>, <p>1,859 세대</p>, <p>2017.05 분양</p>, <p>2019.12 입주</p>, <p class="tag_blue">분양중</p>, <p>기타</p>, <p>41,500만원</p>, <p>10 세대</p>, <p>2017.05 분양</p>, <p>2017.05 입주</p>, <p class="tag_blue">분양중</p>, <p>아파트</p>, <p>22,200 ~ 37,600만원</p>, <p>133 세대</p>, <p>2017.05 분양</p>, <p>2018.10 입주</p>, <p class="tag_blue">분양중</p>, <p>기타</p>, <p>16,800 ~ 31,800만원</p>, <p>10 세대</p>, <p>2017.05 분양</p>, <p>2017.05 입주</p>, <p class="tag_blue">분양중</p>, <p>아파트</p>, <p>55,100 ~ 109,500만원</p>, <p>1,546 세대</p>, <p>2017.05 분양</p>, <p>2020.01 입주</p>, <p class="tag_blue">분양중</p>, <p>오피스텔</p>, <p>21,821 ~ 21,757만원</p>, <p>81 세대</p>, <p>2017.05 분양</p>, <p>2018.07 입주</p>, <p class="tag_blue">분양중</p>, <p>상가</p>, <p>미정 천원</p>, <p>150 점포</p>, <p>2017.05 분양</p>, <p>2018.08 입주</p>, <p class="tag_blue">분양중</p>, <p>기타</p>, <p>39,300 ~ 49,700만원</p>, <p>60 세대</p>, <p>2017.04 분양</p>, <p>2017.06 입주</p>, <p>아파트</p>, <p>아파트</p>, <p>아파트</p>, <p>아파트</p>, <p>아파트</p>, <p>제호 [ 분양정보닷컴 ]</p>, <p>고객센터</p>]


43,600 ~ 57,600만원
31,800 ~ 71,300만원
35,500 ~ 66,200만원
34,700만원
40,800 ~ 57,600만원
15,900 ~ 16,500만원
16,400 ~ 33,200만원
56,200 ~ 100,100만원
41,500만원
22,200 ~ 37,600만원
16,800 ~ 31,800만원
55,100 ~ 109,500만원
21,821 ~ 21,757만원
미정 천원
39,300 ~ 49,700만원


[1947700, 171960, 1385000, 85120, 1289000, 890000, 345000, 2277000, 350500, 240000, 316200, 661000, 826400, 350290, 681580, 828000, 356800, 289800, 497100, 399000, 1058280, 2500000, 731100, 648500, 723300, 149900, 585200, 552800, 729000, 197000, 739000, 299000, 596610, 1043000, 2178000, 545000, 546500, 647400, 2091500, 547700, 655600, 1012000, 685480, 685480, 899000, 6254100, 110000, 858000, 638000, 282000, 205000, 770000, 535500, 275000, 639950, 700000, 939000, 1991000, '43,600 ~ 57,600만원', '31,800 ~ 71,300만원', '35,500 ~ 66,200만원', '34,700만원', '40,800 ~ 57,600만원', '15,900 ~ 16,500만원', '16,400 ~ 33,200만원', '56,200 ~ 100,100만원', '41,500만원', '22,200 ~ 37,600만원', '16,800 ~ 31,800만원', '55,100 ~ 109,500만원', '21,821 ~ 21,757만원', '미정 천원', '39,300 ~ 49,700만원']


[1947700, 171960, 1385000, 85120, 1289000, 890000, 345000, 2277000, 350500, 240000, 316200, 661000, 826400, 350290, 681580, 828000, 356800, 289800, 497100, 399000, 1058280, 2500000, 731100, 648500, 723300, 149900, 585200, 552800, 729000, 197000, 739000, 299000, 596610, 1043000, 2178000, 545000, 546500, 647400, 2091500, 547700, 655600, 1012000, 685480, 685480, 899000, 6254100, 110000, 858000, 638000, 282000, 205000, 770000, 535500, 275000, 639950, 700000, 939000, 1991000, 576000, 713000, 662000, 347000, 576000, 165000, 332000, 1001000, 415000, 376000, 318000, 1095000, 217570, 4390000, 497000]
[19095, 2866, 13578, 1001, 12637, 8725, 5750, 22323, 5841, 4000, 5270, 6480, 8101, 5838, 6682, 8117, 5946, 4830, 4873, 4694, 10375, 29411, 7167, 6357, 7091, 2498, 5737, 5419, 7147, 3283, 7245, 4983, 9943, 10225, 21352, 5343, 5357, 6347, 20504, 5369, 7712, 9921, 6720, 6720, 8813, 61314, 1833, 8411, 6254, 4700, 3416, 7549, 5250, 4583, 6274, 11666, 9205, 19519, 576000, 713000, 662000, 347000, 576000, 165000, 332000, 1001000, 415000, 376000, 318000, 1095000, 217570, 4390000, 497000]
[<p class="arrow"></p>, <p class="arrow"></p>, <p class="arrow"></p>, <p class="tag_blue">분양중</p>, <p>아파트</p>, <p>43,600 ~ 57,600만원</p>, <p>859 세대</p>, <p>2017.06 분양</p>, <p>2019.11 입주</p>, <p class="tag_blue">분양중</p>, <p>아파트</p>, <p>31,800 ~ 71,300만원</p>, <p>1,192 세대</p>, <p>2017.06 분양</p>, <p>2020.06 입주</p>, <p class="tag_blue">분양중</p>, <p>아파트</p>, <p>35,500 ~ 66,200만원</p>, <p>656 세대</p>, <p>2017.06 분양</p>, <p>2020.09 입주</p>, <p class="tag_blue">분양중</p>, <p>기타</p>, <p>34,700만원</p>, <p>34 세대</p>, <p>2017.06 분양</p>, <p>2017.07 입주</p>, <p class="tag_blue">분양중</p>, <p>아파트</p>, <p>40,800 ~ 57,600만원</p>, <p>3,045 세대</p>, <p>2017.06 분양</p>, <p>2020.03 입주</p>, <p class="tag_blue">분양중</p>, <p>오피스텔</p>, <p>15,900 ~ 16,500만원</p>, <p>154 세대</p>, <p>2017.06 분양</p>, <p>2017.10 입주</p>, <p class="tag_blue">분양중</p>, <p>도·생</p>, <p>16,400 ~ 33,200만원</p>, <p>154 세대</p>, <p>2017.06 분양</p>, <p>2018.10 입주</p>, <p class="tag_blue">분양중</p>, <p>아파트</p>, <p>56,200 ~ 100,100만원</p>, <p>1,859 세대</p>, <p>2017.05 분양</p>, <p>2019.12 입주</p>, <p class="tag_blue">분양중</p>, <p>기타</p>, <p>41,500만원</p>, <p>10 세대</p>, <p>2017.05 분양</p>, <p>2017.05 입주</p>, <p class="tag_blue">분양중</p>, <p>아파트</p>, <p>22,200 ~ 37,600만원</p>, <p>133 세대</p>, <p>2017.05 분양</p>, <p>2018.10 입주</p>, <p class="tag_blue">분양중</p>, <p>기타</p>, <p>16,800 ~ 31,800만원</p>, <p>10 세대</p>, <p>2017.05 분양</p>, <p>2017.05 입주</p>, <p class="tag_blue">분양중</p>, <p>아파트</p>, <p>55,100 ~ 109,500만원</p>, <p>1,546 세대</p>, <p>2017.05 분양</p>, <p>2020.01 입주</p>, <p class="tag_blue">분양중</p>, <p>오피스텔</p>, <p>21,821 ~ 21,757만원</p>, <p>81 세대</p>, <p>2017.05 분양</p>, <p>2018.07 입주</p>, <p class="tag_blue">분양중</p>, <p>상가</p>, <p>미정 천원</p>, <p>150 점포</p>, <p>2017.05 분양</p>, <p>2018.08 입주</p>, <p class="tag_blue">분양중</p>, <p>기타</p>, <p>39,300 ~ 49,700만원</p>, <p>60 세대</p>, <p>2017.04 분양</p>, <p>2017.06 입주</p>, <p>아파트</p>, <p>아파트</p>, <p>아파트</p>, <p>아파트</p>, <p>아파트</p>, <p>제호 [ 분양정보닷컴 ]</p>, <p>고객센터</p>]


2017.06 분양
2017.06 분양
2017.06 분양
2017.06 분양
2017.06 분양
2017.06 분양
2017.06 분양
2017.05 분양
2017.05 분양
2017.05 분양
2017.05 분양
2017.05 분양
2017.05 분양
2017.05 분양
2017.04 분양


['2019', '2019', '2019', '2019', '2019', '2019', '2018', '2018', '2018', '2018', '2018', '2018', '2018', '2018', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017.06 분양', '2017.06 분양', '2017.06 분양', '2017.06 분양', '2017.06 분양', '2017.06 분양', '2017.06 분양', '2017.05 분양', '2017.05 분양', '2017.05 분양', '2017.05 분양', '2017.05 분양', '2017.05 분양', '2017.05 분양', '2017.04 분양']


['2019', '2019', '2019', '2019', '2019', '2019', '2018', '2018', '2018', '2018', '2018', '2018', '2018', '2018', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017']

   지역명               규모구분     분양가격  평당분양가격    연도
0   서울        전용면적 102㎡초과  1947700   19095  2019
1   서울         전용면적 60㎡이하   171960    2866  2019
2   서울        전용면적 102㎡초과  1385000   13578  2019
3   서울   전용면적 60㎡초과 85㎡이하    85120    1001  2019
4   서울  전용면적 85㎡초과 102㎡이하  1289000   12637  2019
5   서울        전용면적 102㎡초과   890000    8725  2019
6   서울         전용면적 60㎡이하   345000    5750  2018
7   서울        전용면적 102㎡초과  2277000   22323  2018
8   서울         전용면적 60㎡이하   350500    5841  2018
9   서울         전용면적 60㎡이하   240000    4000  2018
10  서울         전용면적 60㎡이하   316200    5270  2018
11  서울        전용면적 102㎡초과   661000    6480  2018
12  서울        전용면적 102㎡초과   826400    8101  2018
13  서울         전용면적 60㎡이하   350290    5838  2018
14  서울        전용면적 102㎡초과   681580    6682  2017
15  서울        전용면적 102㎡초과   828000    8117  2017
16  서울         전용면적 60㎡이하   356800    5946  2017
17  서울         전용면적 60㎡이하   289800    4830  2017
18  서울        전용면적 102㎡초과   497100    4873  2017
19  서울   전용면적 60㎡초과 85㎡이하   399000    4694  2017
20  서울        전용면적 102㎡초과  1058280   10375  2017
21  서울   전용면적 60㎡초과 85㎡이하  2500000   29411  2017
22  서울        전용면적 102㎡초과   731100    7167  2017
23  서울        전용면적 102㎡초과   648500    6357  2017
24  서울        전용면적 102㎡초과   723300    7091  2017
25  서울         전용면적 60㎡이하   149900    2498  2017
26  서울        전용면적 102㎡초과   585200    5737  2017
27  서울        전용면적 102㎡초과   552800    5419  2017
28  서울        전용면적 102㎡초과   729000    7147  2017
29  서울         전용면적 60㎡이하   197000    3283  2017
..  ..                ...      ...     ...   ...
43  서울        전용면적 102㎡초과   685480    6720  2017
44  서울        전용면적 102㎡초과   899000    8813  2017
45  서울        전용면적 102㎡초과  6254100   61314  2017
46  서울         전용면적 60㎡이하   110000    1833  2017
47  서울        전용면적 102㎡초과   858000    8411  2017
48  서울        전용면적 102㎡초과   638000    6254  2017
49  서울         전용면적 60㎡이하   282000    4700  2017
50  서울         전용면적 60㎡이하   205000    3416  2017
51  서울        전용면적 102㎡초과   770000    7549  2017
52  서울        전용면적 102㎡초과   535500    5250  2017
53  서울         전용면적 60㎡이하   275000    4583  2017
54  서울        전용면적 102㎡초과   639950    6274  2017
55  서울         전용면적 60㎡이하   700000   11666  2017
56  서울        전용면적 102㎡초과   939000    9205  2017
57  서울        전용면적 102㎡초과  1991000   19519  2017
58  서울        전용면적 102㎡초과   576000    5647  2017
59  서울        전용면적 102㎡초과   713000    6990  2017
60  서울   전용면적 60㎡초과 85㎡이하   662000    7788  2017
61  서울   전용면적 60㎡초과 85㎡이하   347000    4082  2017
62  서울        전용면적 102㎡초과   576000    5647  2017
63  서울         전용면적 60㎡이하   165000    2750  2017
64  서울         전용면적 60㎡이하   332000    5533  2017
65  서울        전용면적 102㎡초과  1001000    9813  2017
66  서울   전용면적 60㎡초과 85㎡이하   415000    4882  2017
67  서울         전용면적 60㎡이하   376000    6266  2017
68  서울   전용면적 60㎡초과 85㎡이하   318000    3741  2017
69  서울        전용면적 102㎡초과  1095000   10735  2017
70  서울         전용면적 60㎡이하   217570    3626  2017
71  서울        전용면적 102㎡초과  4390000   43039  2017
72  서울         전용면적 60㎡이하   497000    8283  2017

[73 rows x 5 columns]

In [47]:
#[6 page]
def get_html(url) :
    html = ""
    resp = requests.get(url)
    if resp.status_code == 200 :
        html = resp.text
    return html
html = get_html('http://www.boonyang24.com/?sub=boonyang_info/info_list&do1=&si1=&boonryu01=&boonryu02=&page=6&keyword=&tp=&cate=&area_code=&work_year=&hyun_cate=')
soup = BeautifulSoup(html, 'html.parser')
boonyang = soup.find("div",{"class":"list_type_boonyang"})
#----------------------------------------------------------------------

#지역에 대한 리스트
Citycell = {}

w_city5 = soup.find_all('td', {'class':'subject'})
#다 서울이기 때문에 모든 리스트의 요소를 '서울'로 간단하게 바꿔줌. 

for i in range(0, 15):   #0~14
    w_city5[i]
    print(w_city5[i].text)
print('\n')

for i in range(0, 15):
    w_city5[i] = "서울"
for i in range(0, 15):
    w_city_l.append(w_city5[i])
    
print(w_city_l)
print('\n')

Citycell['지역명'] = w_city_l
sd = pd.DataFrame(Citycell)
sd = sd[['지역명']]

#----------------------------------------------------------------------
#----------------------------------------------------------------------
#규모에 대한 내용.
# "전용면적 60㎡이하" = 60 ,   "전용면적 60㎡초과 85㎡이하" = 85
# "전용면적 85㎡초과 102㎡이하" = 85,  "전용면적 102㎡초과" =102
w_size5 = soup.find_all('b')
for i in range(0, 15): #30개
    del w_size5[i]
w_size5[0] = "전용면적 102㎡초과"
w_size5[1] = "전용면적 102㎡초과"
w_size5[2] = "전용면적 85㎡초과 102㎡이하"
w_size5[3] = "전용면적 60㎡이하"
w_size5[4] = "전용면적 60㎡초과 85㎡이하"
w_size5[5] = "전용면적 60㎡초과 85㎡이하"
w_size5[6] = "전용면적 85㎡초과 102㎡이하"
w_size5[7] = "전용면적 102㎡초과"
w_size5[8] = "전용면적 85㎡초과 102㎡이하"
w_size5[9] = "전용면적 85㎡초과 102㎡이하"
w_size5[10] = "전용면적 102㎡초과"
w_size5[11] = "전용면적 102㎡초과"
w_size5[12] = "전용면적 60㎡초과 85㎡이하"
w_size5[13] = "전용면적 60㎡초과 85㎡이하"
w_size5[14] = "전용면적 60㎡초과 85㎡이하"
print(w_size5)

for i in range(0, 15):
    w_size_l.append(w_size5[i])
print(w_size_l)

Citycell['지역명'] = w_city_l
Citycell['규모구분'] = w_size_l
sd = pd.DataFrame(Citycell)
sd = sd[['지역명', '규모구분']]

#----------------------------------------------------------------------
print('\n')
w_price5 = soup.find_all('p')
print(w_price5)               #6번째 주기로 가격정보가 나오는걸 알 수 있다.
                            #'미정'처리된 두 지역은 빼고 생각하였다.
print('\n')
for i in range(1,16):
    print(w_price5[6*i-1].text)   
    w_price_l.extend(w_price5[6*i-1])   #등차수열 이용.
print('\n')
print(w_price_l)
    
#Citycell['지역명'] = w_city_l
#Citycell['규모구분'] = w_size_l
Citycell['분양가격'] = w_price_l
sd = pd.DataFrame(Citycell)
sd = sd[['지역명', '규모구분','분양가격']]

#----------------------------------------------------------------------
#크롤링한 사이트는 단위가 '만 원'이다.
#본래 데이터분석을 한 자료의 단위는 '천 원'이므로 끝에 0을 더 붙여서 할당하였다.
w_price_l[73] = 399000
w_price_l[74] = 2073800
w_price_l[75] = 315000
w_price_l[76] = 370000
w_price_l[77] = 362000
w_price_l[78] = 359000
w_price_l[79] = 364000
w_price_l[80] = 698000
w_price_l[81] = 274000
w_price_l[82] = 339000
w_price_l[83] = 2135070
w_price_l[84] = 1991500
w_price_l[85] = 349000
w_price_l[86] = 363000
w_price_l[87] = 352000

print('\n')
print(w_price_l)
#pandas 처리
sd = pd.DataFrame(Citycell)
sd = sd[['지역명', '규모구분','분양가격']]

#----------------------------------------------------------------------
#평당분양가격
sd['분양가격'] = pd.to_numeric(w_price_l, errors = 'coerce')

for i in range(73,88):
    w_square.append(w_price_l[i])
print(w_square)

w_square[73] = int(399000/102)
w_square[74] = int(2073800/102)
w_square[75] = int(315000/85)
w_square[76] = int(370000/60)
w_square[77] = int(362000/85)
w_square[78] = int(359000/85)
w_square[79] = int(364000/85)
w_square[80] = int(698000/102)
w_square[81] = int(274000/85)
w_square[82] = int(339000/85)
w_square[83] = int(2135070/102)
w_square[84] = int(1991500/102)
w_square[85] = int(349000/85)
w_square[86] = int(363000/85)
w_square[87] = int(352000/85)

Citycell['평당분양가격'] = w_square
sd = pd.DataFrame(Citycell)
sd = sd[['지역명', '규모구분','분양가격','평당분양가격']]

#----------------------------------------------------------------------

#연도에 대한 리스트 필요.
w_year5 = soup.find_all('p')
print(w_year5)
print('\n')
#7, 13, 19, 25 a+(n-1)d
#7+(i-1)*6        // 등차수열 이용.
for i in range(1,16):
    print(w_year5[7+(i-1)*6].text)    
    w_year_l.extend(w_year5[7+(i-1)*6])
    
print('\n')
print(w_year_l)

for i in range(58,73):
    w_year_l[i] = '2017'
print('\n')
print(w_year_l)

#pandas 처리
Citycell['지역명'] = w_city_l
Citycell['규모구분'] = w_size_l
Citycell['가격'] = w_price_l
Citycell['연도'] = w_year_l

sd = pd.DataFrame(Citycell)
sd = sd[['지역명', '규모구분','분양가격','평당분양가격', '연도']]
sd

메트로타운7차 서울시 관악구 신림동 신림동 1483-8
대치3차아이파크 서울특별시 강남구 대치동 945-20
동화아트빌 서울 서대문구 북가좌동 294-20
다윈팰리스 서울 송파구 문정동 25-3
신성9차 서울 강북구 미아동 133-125
한경내담채 서울 은평구 응암동 87-3
예다움 서울 도봉구 쌍문동 533-41
힐스테이트암사 서울특별시 강동구 암사동 514
목동M타운 서울시 양천구 신월동 512-1
청우컨스빌 서울 중랑구 면목동 373-10
역삼역 센트럴 푸르지오 시티 상가 서울특별시 강남구 역삼동 719-24
삼성동롯데캐슬클라쎄 서울특별시 강남구 삼성동 141-8
상산노블하임 서울 동작구 사당동 1050-16
세종캐슬 서울 송파구 문정동 113-4
엘파라시오6차 서울 동작구 사당동 278-103


['서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울']


['전용면적 102㎡초과', '전용면적 102㎡초과', '전용면적 85㎡초과 102㎡이하', '전용면적 60㎡이하', '전용면적 60㎡초과 85㎡이하', '전용면적 60㎡초과 85㎡이하', '전용면적 85㎡초과 102㎡이하', '전용면적 102㎡초과', '전용면적 85㎡초과 102㎡이하', '전용면적 85㎡초과 102㎡이하', '전용면적 102㎡초과', '전용면적 102㎡초과', '전용면적 60㎡초과 85㎡이하', '전용면적 60㎡초과 85㎡이하', '전용면적 60㎡초과 85㎡이하']
['전용면적 102㎡초과', '전용면적 60㎡이하', '전용면적 102㎡초과', '전용면적 60㎡초과 85㎡이하', '전용면적 85㎡초과 102㎡이하', '전용면적 102㎡초과', '전용면적 60㎡이하', '전용면적 102㎡초과', '전용면적 60㎡이하', '전용면적 60㎡이하', '전용면적 60㎡이하', '전용면적 102㎡초과', '전용면적 102㎡초과', '전용면적 60㎡이하', '전용면적 102㎡초과', '전용면적 102㎡초과', '전용면적 60㎡이하', '전용면적 60㎡이하', '전용면적 102㎡초과', '전용면적 60㎡초과 85㎡이하', '전용면적 102㎡초과', '전용면적 60㎡초과 85㎡이하', '전용면적 102㎡초과', '전용면적 102㎡초과', '전용면적 102㎡초과', '전용면적 60㎡이하', '전용면적 102㎡초과', '전용면적 102㎡초과', '전용면적 102㎡초과', '전용면적 60㎡이하', '전용면적 102㎡초과', '전용면적 60㎡이하', '전용면적 60㎡초과 85㎡이하', '전용면적 102㎡초과', '전용면적 102㎡초과', '전용면적 102㎡초과', '전용면적 102㎡초과', '전용면적 102㎡초과', '전용면적 102㎡초과', '전용면적 102㎡초과', '전용면적 85㎡초과 102㎡이하', '전용면적 102㎡초과', '전용면적 102㎡초과', '전용면적 102㎡초과', '전용면적 102㎡초과', '전용면적 102㎡초과', '전용면적 60㎡이하', '전용면적 102㎡초과', '전용면적 102㎡초과', '전용면적 60㎡이하', '전용면적 60㎡이하', '전용면적 102㎡초과', '전용면적 102㎡초과', '전용면적 60㎡이하', '전용면적 102㎡초과', '전용면적 60㎡이하', '전용면적 102㎡초과', '전용면적 102㎡초과', '전용면적 102㎡초과', '전용면적 102㎡초과', '전용면적 60㎡초과 85㎡이하', '전용면적 60㎡초과 85㎡이하', '전용면적 102㎡초과', '전용면적 60㎡이하', '전용면적 60㎡이하', '전용면적 102㎡초과', '전용면적 60㎡초과 85㎡이하', '전용면적 60㎡이하', '전용면적 60㎡초과 85㎡이하', '전용면적 102㎡초과', '전용면적 60㎡이하', '전용면적 102㎡초과', '전용면적 60㎡이하', '전용면적 102㎡초과', '전용면적 102㎡초과', '전용면적 85㎡초과 102㎡이하', '전용면적 60㎡이하', '전용면적 60㎡초과 85㎡이하', '전용면적 60㎡초과 85㎡이하', '전용면적 85㎡초과 102㎡이하', '전용면적 102㎡초과', '전용면적 85㎡초과 102㎡이하', '전용면적 85㎡초과 102㎡이하', '전용면적 102㎡초과', '전용면적 102㎡초과', '전용면적 60㎡초과 85㎡이하', '전용면적 60㎡초과 85㎡이하', '전용면적 60㎡초과 85㎡이하']


[<p class="arrow"></p>, <p class="arrow"></p>, <p class="arrow"></p>, <p class="tag_blue">분양중</p>, <p>도·생</p>, <p>22,900 ~ 39,900만원</p>, <p>15 세대</p>, <p>2017.04 분양</p>, <p>2017.04 입주</p>, <p class="tag_blue">분양중</p>, <p>오피스텔</p>, <p>31,650 ~ 207,380만원</p>, <p>207 세대</p>, <p>2017.04 분양</p>, <p>2020.01 입주</p>, <p class="tag_blue">분양중</p>, <p>기타</p>, <p>26,800 ~ 31,500만원</p>, <p>16 세대</p>, <p>2017.04 분양</p>, <p>2017.04 입주</p>, <p class="tag_blue">분양중</p>, <p>도·생</p>, <p>27,500 ~ 37,000만원</p>, <p>29 세대</p>, <p>2017.04 분양</p>, <p>2017.04 입주</p>, <p class="tag_blue">분양중</p>, <p>도·생</p>, <p>23,200 ~ 36,200만원</p>, <p>13 세대</p>, <p>2017.04 분양</p>, <p>2017.04 입주</p>, <p class="tag_blue">분양중</p>, <p>기타</p>, <p>26,000 ~ 35,900만원</p>, <p>10 세대</p>, <p>2017.04 분양</p>, <p>2017.04 입주</p>, <p class="tag_blue">분양중</p>, <p>기타</p>, <p>27,900 ~ 36,400만원</p>, <p>71 세대</p>, <p>2017.04 분양</p>, <p>2017.04 입주</p>, <p class="tag_blue">분양중</p>, <p>아파트</p>, <p>50,100 ~ 69,800만원</p>, <p>460 세대</p>, <p>2017.04 분양</p>, <p>2019.11 입주</p>, <p class="tag_blue">분양중</p>, <p>도·생</p>, <p>16,400 ~ 27,400만원</p>, <p>35 세대</p>, <p>2017.04 분양</p>, <p>2017.04 입주</p>, <p class="tag_blue">분양중</p>, <p>기타</p>, <p>23,300 ~ 33,900만원</p>, <p>15 세대</p>, <p>2017.04 분양</p>, <p>2017.05 입주</p>, <p class="tag_blue">분양중</p>, <p>상가</p>, <p>35,600 ~ 213,507만원</p>, <p>45 점포</p>, <p>2017.04 분양</p>, <p>2019.03 입주</p>, <p class="tag_blue">분양중</p>, <p>오피스텔</p>, <p>28,850 ~ 199,150만원</p>, <p>287 세대</p>, <p>2017.03 분양</p>, <p>2019.09 입주</p>, <p class="tag_blue">분양중</p>, <p>기타</p>, <p>25,900 ~ 34,900만원</p>, <p>16 세대</p>, <p>2017.03 분양</p>, <p>2017.03 입주</p>, <p class="tag_blue">분양중</p>, <p>도·생</p>, <p>33,300 ~ 36,300만원</p>, <p>29 세대</p>, <p>2017.03 분양</p>, <p>2017.03 입주</p>, <p class="tag_blue">분양중</p>, <p>기타</p>, <p>28,500 ~ 35,200만원</p>, <p>8 세대</p>, <p>2017.03 분양</p>, <p>2017.03 입주</p>, <p>아파트</p>, <p>아파트</p>, <p>아파트</p>, <p>아파트</p>, <p>아파트</p>, <p>제호 [ 분양정보닷컴 ]</p>, <p>고객센터</p>]


22,900 ~ 39,900만원
31,650 ~ 207,380만원
26,800 ~ 31,500만원
27,500 ~ 37,000만원
23,200 ~ 36,200만원
26,000 ~ 35,900만원
27,900 ~ 36,400만원
50,100 ~ 69,800만원
16,400 ~ 27,400만원
23,300 ~ 33,900만원
35,600 ~ 213,507만원
28,850 ~ 199,150만원
25,900 ~ 34,900만원
33,300 ~ 36,300만원
28,500 ~ 35,200만원


[1947700, 171960, 1385000, 85120, 1289000, 890000, 345000, 2277000, 350500, 240000, 316200, 661000, 826400, 350290, 681580, 828000, 356800, 289800, 497100, 399000, 1058280, 2500000, 731100, 648500, 723300, 149900, 585200, 552800, 729000, 197000, 739000, 299000, 596610, 1043000, 2178000, 545000, 546500, 647400, 2091500, 547700, 655600, 1012000, 685480, 685480, 899000, 6254100, 110000, 858000, 638000, 282000, 205000, 770000, 535500, 275000, 639950, 700000, 939000, 1991000, 576000, 713000, 662000, 347000, 576000, 165000, 332000, 1001000, 415000, 376000, 318000, 1095000, 217570, 4390000, 497000, '22,900 ~ 39,900만원', '31,650 ~ 207,380만원', '26,800 ~ 31,500만원', '27,500 ~ 37,000만원', '23,200 ~ 36,200만원', '26,000 ~ 35,900만원', '27,900 ~ 36,400만원', '50,100 ~ 69,800만원', '16,400 ~ 27,400만원', '23,300 ~ 33,900만원', '35,600 ~ 213,507만원', '28,850 ~ 199,150만원', '25,900 ~ 34,900만원', '33,300 ~ 36,300만원', '28,500 ~ 35,200만원']


[1947700, 171960, 1385000, 85120, 1289000, 890000, 345000, 2277000, 350500, 240000, 316200, 661000, 826400, 350290, 681580, 828000, 356800, 289800, 497100, 399000, 1058280, 2500000, 731100, 648500, 723300, 149900, 585200, 552800, 729000, 197000, 739000, 299000, 596610, 1043000, 2178000, 545000, 546500, 647400, 2091500, 547700, 655600, 1012000, 685480, 685480, 899000, 6254100, 110000, 858000, 638000, 282000, 205000, 770000, 535500, 275000, 639950, 700000, 939000, 1991000, 576000, 713000, 662000, 347000, 576000, 165000, 332000, 1001000, 415000, 376000, 318000, 1095000, 217570, 4390000, 497000, 399000, 2073800, 315000, 370000, 362000, 359000, 364000, 698000, 274000, 339000, 2135070, 1991500, 349000, 363000, 352000]
[19095, 2866, 13578, 1001, 12637, 8725, 5750, 22323, 5841, 4000, 5270, 6480, 8101, 5838, 6682, 8117, 5946, 4830, 4873, 4694, 10375, 29411, 7167, 6357, 7091, 2498, 5737, 5419, 7147, 3283, 7245, 4983, 9943, 10225, 21352, 5343, 5357, 6347, 20504, 5369, 7712, 9921, 6720, 6720, 8813, 61314, 1833, 8411, 6254, 4700, 3416, 7549, 5250, 4583, 6274, 11666, 9205, 19519, 5647, 6990, 7788, 4082, 5647, 2750, 5533, 9813, 4882, 6266, 3741, 10735, 3626, 43039, 8283, 399000, 2073800, 315000, 370000, 362000, 359000, 364000, 698000, 274000, 339000, 2135070, 1991500, 349000, 363000, 352000]
[<p class="arrow"></p>, <p class="arrow"></p>, <p class="arrow"></p>, <p class="tag_blue">분양중</p>, <p>도·생</p>, <p>22,900 ~ 39,900만원</p>, <p>15 세대</p>, <p>2017.04 분양</p>, <p>2017.04 입주</p>, <p class="tag_blue">분양중</p>, <p>오피스텔</p>, <p>31,650 ~ 207,380만원</p>, <p>207 세대</p>, <p>2017.04 분양</p>, <p>2020.01 입주</p>, <p class="tag_blue">분양중</p>, <p>기타</p>, <p>26,800 ~ 31,500만원</p>, <p>16 세대</p>, <p>2017.04 분양</p>, <p>2017.04 입주</p>, <p class="tag_blue">분양중</p>, <p>도·생</p>, <p>27,500 ~ 37,000만원</p>, <p>29 세대</p>, <p>2017.04 분양</p>, <p>2017.04 입주</p>, <p class="tag_blue">분양중</p>, <p>도·생</p>, <p>23,200 ~ 36,200만원</p>, <p>13 세대</p>, <p>2017.04 분양</p>, <p>2017.04 입주</p>, <p class="tag_blue">분양중</p>, <p>기타</p>, <p>26,000 ~ 35,900만원</p>, <p>10 세대</p>, <p>2017.04 분양</p>, <p>2017.04 입주</p>, <p class="tag_blue">분양중</p>, <p>기타</p>, <p>27,900 ~ 36,400만원</p>, <p>71 세대</p>, <p>2017.04 분양</p>, <p>2017.04 입주</p>, <p class="tag_blue">분양중</p>, <p>아파트</p>, <p>50,100 ~ 69,800만원</p>, <p>460 세대</p>, <p>2017.04 분양</p>, <p>2019.11 입주</p>, <p class="tag_blue">분양중</p>, <p>도·생</p>, <p>16,400 ~ 27,400만원</p>, <p>35 세대</p>, <p>2017.04 분양</p>, <p>2017.04 입주</p>, <p class="tag_blue">분양중</p>, <p>기타</p>, <p>23,300 ~ 33,900만원</p>, <p>15 세대</p>, <p>2017.04 분양</p>, <p>2017.05 입주</p>, <p class="tag_blue">분양중</p>, <p>상가</p>, <p>35,600 ~ 213,507만원</p>, <p>45 점포</p>, <p>2017.04 분양</p>, <p>2019.03 입주</p>, <p class="tag_blue">분양중</p>, <p>오피스텔</p>, <p>28,850 ~ 199,150만원</p>, <p>287 세대</p>, <p>2017.03 분양</p>, <p>2019.09 입주</p>, <p class="tag_blue">분양중</p>, <p>기타</p>, <p>25,900 ~ 34,900만원</p>, <p>16 세대</p>, <p>2017.03 분양</p>, <p>2017.03 입주</p>, <p class="tag_blue">분양중</p>, <p>도·생</p>, <p>33,300 ~ 36,300만원</p>, <p>29 세대</p>, <p>2017.03 분양</p>, <p>2017.03 입주</p>, <p class="tag_blue">분양중</p>, <p>기타</p>, <p>28,500 ~ 35,200만원</p>, <p>8 세대</p>, <p>2017.03 분양</p>, <p>2017.03 입주</p>, <p>아파트</p>, <p>아파트</p>, <p>아파트</p>, <p>아파트</p>, <p>아파트</p>, <p>제호 [ 분양정보닷컴 ]</p>, <p>고객센터</p>]


2017.04 분양
2017.04 분양
2017.04 분양
2017.04 분양
2017.04 분양
2017.04 분양
2017.04 분양
2017.04 분양
2017.04 분양
2017.04 분양
2017.04 분양
2017.03 분양
2017.03 분양
2017.03 분양
2017.03 분양


['2019', '2019', '2019', '2019', '2019', '2019', '2018', '2018', '2018', '2018', '2018', '2018', '2018', '2018', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017.04 분양', '2017.04 분양', '2017.04 분양', '2017.04 분양', '2017.04 분양', '2017.04 분양', '2017.04 분양', '2017.04 분양', '2017.04 분양', '2017.04 분양', '2017.04 분양', '2017.03 분양', '2017.03 분양', '2017.03 분양', '2017.03 분양']


['2019', '2019', '2019', '2019', '2019', '2019', '2018', '2018', '2018', '2018', '2018', '2018', '2018', '2018', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017.04 분양', '2017.04 분양', '2017.04 분양', '2017.04 분양', '2017.04 분양', '2017.04 분양', '2017.04 분양', '2017.04 분양', '2017.04 분양', '2017.04 분양', '2017.04 분양', '2017.03 분양', '2017.03 분양', '2017.03 분양', '2017.03 분양']

   지역명               규모구분     분양가격  평당분양가격          연도
0   서울        전용면적 102㎡초과  1947700   19095        2019
1   서울         전용면적 60㎡이하   171960    2866        2019
2   서울        전용면적 102㎡초과  1385000   13578        2019
3   서울   전용면적 60㎡초과 85㎡이하    85120    1001        2019
4   서울  전용면적 85㎡초과 102㎡이하  1289000   12637        2019
5   서울        전용면적 102㎡초과   890000    8725        2019
6   서울         전용면적 60㎡이하   345000    5750        2018
7   서울        전용면적 102㎡초과  2277000   22323        2018
8   서울         전용면적 60㎡이하   350500    5841        2018
9   서울         전용면적 60㎡이하   240000    4000        2018
10  서울         전용면적 60㎡이하   316200    5270        2018
11  서울        전용면적 102㎡초과   661000    6480        2018
12  서울        전용면적 102㎡초과   826400    8101        2018
13  서울         전용면적 60㎡이하   350290    5838        2018
14  서울        전용면적 102㎡초과   681580    6682        2017
15  서울        전용면적 102㎡초과   828000    8117        2017
16  서울         전용면적 60㎡이하   356800    5946        2017
17  서울         전용면적 60㎡이하   289800    4830        2017
18  서울        전용면적 102㎡초과   497100    4873        2017
19  서울   전용면적 60㎡초과 85㎡이하   399000    4694        2017
20  서울        전용면적 102㎡초과  1058280   10375        2017
21  서울   전용면적 60㎡초과 85㎡이하  2500000   29411        2017
22  서울        전용면적 102㎡초과   731100    7167        2017
23  서울        전용면적 102㎡초과   648500    6357        2017
24  서울        전용면적 102㎡초과   723300    7091        2017
25  서울         전용면적 60㎡이하   149900    2498        2017
26  서울        전용면적 102㎡초과   585200    5737        2017
27  서울        전용면적 102㎡초과   552800    5419        2017
28  서울        전용면적 102㎡초과   729000    7147        2017
29  서울         전용면적 60㎡이하   197000    3283        2017
..  ..                ...      ...     ...         ...
58  서울        전용면적 102㎡초과   576000    5647        2017
59  서울        전용면적 102㎡초과   713000    6990        2017
60  서울   전용면적 60㎡초과 85㎡이하   662000    7788        2017
61  서울   전용면적 60㎡초과 85㎡이하   347000    4082        2017
62  서울        전용면적 102㎡초과   576000    5647        2017
63  서울         전용면적 60㎡이하   165000    2750        2017
64  서울         전용면적 60㎡이하   332000    5533        2017
65  서울        전용면적 102㎡초과  1001000    9813        2017
66  서울   전용면적 60㎡초과 85㎡이하   415000    4882        2017
67  서울         전용면적 60㎡이하   376000    6266        2017
68  서울   전용면적 60㎡초과 85㎡이하   318000    3741        2017
69  서울        전용면적 102㎡초과  1095000   10735        2017
70  서울         전용면적 60㎡이하   217570    3626        2017
71  서울        전용면적 102㎡초과  4390000   43039        2017
72  서울         전용면적 60㎡이하   497000    8283        2017
73  서울        전용면적 102㎡초과   399000    3911  2017.04 분양
74  서울        전용면적 102㎡초과  2073800   20331  2017.04 분양
75  서울  전용면적 85㎡초과 102㎡이하   315000    3705  2017.04 분양
76  서울         전용면적 60㎡이하   370000    6166  2017.04 분양
77  서울   전용면적 60㎡초과 85㎡이하   362000    4258  2017.04 분양
78  서울   전용면적 60㎡초과 85㎡이하   359000    4223  2017.04 분양
79  서울  전용면적 85㎡초과 102㎡이하   364000    4282  2017.04 분양
80  서울        전용면적 102㎡초과   698000    6843  2017.04 분양
81  서울  전용면적 85㎡초과 102㎡이하   274000    3223  2017.04 분양
82  서울  전용면적 85㎡초과 102㎡이하   339000    3988  2017.04 분양
83  서울        전용면적 102㎡초과  2135070   20932  2017.04 분양
84  서울        전용면적 102㎡초과  1991500   19524  2017.03 분양
85  서울   전용면적 60㎡초과 85㎡이하   349000    4105  2017.03 분양
86  서울   전용면적 60㎡초과 85㎡이하   363000    4270  2017.03 분양
87  서울   전용면적 60㎡초과 85㎡이하   352000    4141  2017.03 분양

[88 rows x 5 columns]

In [49]:
#[7 page]
def get_html(url) :
    html = ""
    resp = requests.get(url)
    if resp.status_code == 200 :
        html = resp.text
    return html
html = get_html('http://www.boonyang24.com/?sub=boonyang_info/info_list&do1=&si1=&boonryu01=&boonryu02=&page=7&keyword=&tp=&cate=&area_code=&work_year=&hyun_cate=')
soup = BeautifulSoup(html, 'html.parser')
boonyang = soup.find("div",{"class":"list_type_boonyang"})
#----------------------------------------------------------------------

#지역에 대한 리스트
Citycell = {}

w_city6 = soup.find_all('td', {'class':'subject'})
#다 서울이기 때문에 모든 리스트의 요소를 '서울'로 간단하게 바꿔줌. 

for i in range(0, 15):   #0~14
    w_city6[i]
    print(w_city6[i].text)
print('\n')

for i in range(0, 15):
    w_city6[i] = "서울"
for i in range(0, 15):
    w_city_l.append(w_city6[i])
    
print(w_city_l)
print('\n')

Citycell['지역명'] = w_city_l
sd = pd.DataFrame(Citycell)
sd = sd[['지역명']]

#----------------------------------------------------------------------
#----------------------------------------------------------------------
#규모에 대한 내용.
# "전용면적 60㎡이하" = 60 ,   "전용면적 60㎡초과 85㎡이하" = 85
# "전용면적 85㎡초과 102㎡이하" = 85,  "전용면적 102㎡초과" =102
w_size6 = soup.find_all('b')
for i in range(0, 12):  #27개
    del w_size6[i]
w_size6[0] = "전용면적 60㎡이하"
w_size6[1] = "전용면적 60㎡초과 85㎡이하"
w_size6[2] = "전용면적 60㎡초과 85㎡이하"
w_size6[3] = "전용면적 60㎡초과 85㎡이하"
w_size6[4] = "전용면적 60㎡이하"
w_size6[5] = "전용면적 60㎡초과 85㎡이하"
w_size6[6] = "전용면적 60㎡이하"
w_size6[7] = "전용면적 60㎡초과 85㎡이하"
w_size6[8] = "전용면적 102㎡초과"
w_size6[9] = "전용면적 60㎡초과 85㎡이하"
w_size6[10] = "전용면적 102㎡초과"
w_size6[11] = "전용면적 102㎡초과"
w_size6[12] = "전용면적 60㎡이하"
w_size6[13] = "전용면적 60㎡이하"
w_size6[14] = "전용면적 60㎡초과 85㎡이하"
print(w_size6)

for i in range(0, 15):
    w_size_l.append(w_size6[i])
print(w_size_l)
Citycell['지역명'] = w_city_l
Citycell['규모구분'] = w_size_l
sd = pd.DataFrame(Citycell)
sd = sd[['지역명', '규모구분']]

#----------------------------------------------------------------------
print('\n')
w_price6 = soup.find_all('p')
print(w_price6)               #6번째 주기로 가격정보가 나오는걸 알 수 있다.
                            #'미정'처리된 두 지역은 빼고 생각하였다.
print('\n')
for i in range(1,16):
    print(w_price6[6*i-1].text)   
    w_price_l.extend(w_price6[6*i-1])   #등차수열 이용.
print('\n')
print(w_price_l)
    
Citycell['지역명'] = w_city_l
Citycell['규모구분'] = w_size_l
Citycell['분양가격'] = w_price_l
sd = pd.DataFrame(Citycell)
sd = sd[['지역명', '규모구분','분양가격']]

#----------------------------------------------------------------------
#크롤링한 사이트는 단위가 '만 원'이다.
#본래 데이터분석을 한 자료의 단위는 '천 원'이므로 끝에 0을 더 붙여서 할당하였다.
w_price_l[88] = 249000
w_price_l[89] = 288000
w_price_l[90] = 285000
w_price_l[91] = 255000
w_price_l[92] = 199000
w_price_l[93] = 269000
w_price_l[94] = 210000
w_price_l[95] = 318000
w_price_l[96] = 622000
w_price_l[97] = 239000
w_price_l[98] = 620000
w_price_l[99] = 572100
w_price_l[100] = 278000
w_price_l[101] = 279000
w_price_l[102] = 269000

print('\n')
print(w_price_l)
#pandas 처리
sd = pd.DataFrame(Citycell)
sd = sd[['지역명', '규모구분','분양가격']]

#----------------------------------------------------------------------
#평당분양가격
sd['분양가격'] = pd.to_numeric(w_price_l, errors = 'coerce')

for i in range(88,103):
    w_square.append(w_price_l[i])
print(w_square)
w_square[88] = int(249000/60)
w_square[89] = int(288000/85)
w_square[90] = int(285000/85)
w_square[91] = int(255000/85)
w_square[92] = int(199000/60)
w_square[93] = int(269000/85)
w_square[94] = int(210000/60)
w_square[95] = int(318000/85)
w_square[96] = int(622000/102)
w_square[97] = int(239000/85)
w_square[98] = int(620000/102)
w_square[99] = int(572100/102)
w_square[100] = int(278000/60)
w_square[101] = int(279000/60)
w_square[102] = int(269000/85)

Citycell['평당분양가격'] = w_square
sd = pd.DataFrame(Citycell)
sd = sd[['지역명', '규모구분','분양가격','평당분양가격']]

#----------------------------------------------------------------------

#연도에 대한 리스트 필요.
w_year6 = soup.find_all('p')
print(w_year6)
print('\n')
#7, 13, 19, 25 a+(n-1)d
#7+(i-1)*6        // 등차수열 이용.
for i in range(1,16):
    print(w_year6[7+(i-1)*6].text)    
    w_year_l.extend(w_year6[7+(i-1)*6])
    
print('\n')
print(w_year_l)

for i in range(88,103):
    w_year_l[i] = '2017'
print('\n')
print(w_year_l)

#pandas 처리
Citycell['지역명'] = w_city_l
Citycell['규모구분'] = w_size_l
Citycell['가격'] = w_price_l
Citycell['연도'] = w_year_l

sd = pd.DataFrame(Citycell)
sd = sd[['지역명', '규모구분','분양가격','평당분양가격', '연도']]
sd

샤론인텔리안 서울시 목동 324-37
뫼비우스 서울 강서구 화곡동 350-10
연승카운티 [빌라/연립] 서울특별시 강북구 미아동 223-29
한신빌라트59차 [빌라/연립]  서울특별시 강북구 수유동 169-34
우영채움빌 서울특별시 구로구 고척동 164-114
세인트빌 [빌라/연립] 서울특별시 영등포구 당산동1가 236
동원프라우드2차 서울 중랑구 묵동 239-84
경원에이스 서울 은평구 녹번동 105-2
꿈의숲 효성해링턴플레이스 서울시 강북구 미아9동 3-770
한양리츠빌 서울 관악구 신림동 646-232
광진파밀리에포레시티 서울 광진구 화양동 489번지
백련산SK뷰아이파크 서울특별시 은평구 응암로28길
블리스다임빌 서울 영등포구 당산동1가 144
라임스빌 서울 관악구 신림동 650-22
빌라엔 서울 양천구 신월동 18-11


['서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울']


['전용면적 60㎡이하', '전용면적 60㎡초과 85㎡이하', '전용면적 60㎡초과 85㎡이하', '전용면적 60㎡초과 85㎡이하', '전용면적 60㎡이하', '전용면적 60㎡초과 85㎡이하', '전용면적 60㎡이하', '전용면적 60㎡초과 85㎡이하', '전용면적 102㎡초과', '전용면적 60㎡초과 85㎡이하', '전용면적 102㎡초과', '전용면적 102㎡초과', '전용면적 60㎡이하', '전용면적 60㎡이하', '전용면적 60㎡초과 85㎡이하']
['전용면적 102㎡초과', '전용면적 60㎡이하', '전용면적 102㎡초과', '전용면적 60㎡초과 85㎡이하', '전용면적 85㎡초과 102㎡이하', '전용면적 102㎡초과', '전용면적 60㎡이하', '전용면적 102㎡초과', '전용면적 60㎡이하', '전용면적 60㎡이하', '전용면적 60㎡이하', '전용면적 102㎡초과', '전용면적 102㎡초과', '전용면적 60㎡이하', '전용면적 102㎡초과', '전용면적 102㎡초과', '전용면적 60㎡이하', '전용면적 60㎡이하', '전용면적 102㎡초과', '전용면적 60㎡초과 85㎡이하', '전용면적 102㎡초과', '전용면적 60㎡초과 85㎡이하', '전용면적 102㎡초과', '전용면적 102㎡초과', '전용면적 102㎡초과', '전용면적 60㎡이하', '전용면적 102㎡초과', '전용면적 102㎡초과', '전용면적 102㎡초과', '전용면적 60㎡이하', '전용면적 102㎡초과', '전용면적 60㎡이하', '전용면적 60㎡초과 85㎡이하', '전용면적 102㎡초과', '전용면적 102㎡초과', '전용면적 102㎡초과', '전용면적 102㎡초과', '전용면적 102㎡초과', '전용면적 102㎡초과', '전용면적 102㎡초과', '전용면적 85㎡초과 102㎡이하', '전용면적 102㎡초과', '전용면적 102㎡초과', '전용면적 102㎡초과', '전용면적 102㎡초과', '전용면적 102㎡초과', '전용면적 60㎡이하', '전용면적 102㎡초과', '전용면적 102㎡초과', '전용면적 60㎡이하', '전용면적 60㎡이하', '전용면적 102㎡초과', '전용면적 102㎡초과', '전용면적 60㎡이하', '전용면적 102㎡초과', '전용면적 60㎡이하', '전용면적 102㎡초과', '전용면적 102㎡초과', '전용면적 102㎡초과', '전용면적 102㎡초과', '전용면적 60㎡초과 85㎡이하', '전용면적 60㎡초과 85㎡이하', '전용면적 102㎡초과', '전용면적 60㎡이하', '전용면적 60㎡이하', '전용면적 102㎡초과', '전용면적 60㎡초과 85㎡이하', '전용면적 60㎡이하', '전용면적 60㎡초과 85㎡이하', '전용면적 102㎡초과', '전용면적 60㎡이하', '전용면적 102㎡초과', '전용면적 60㎡이하', '전용면적 102㎡초과', '전용면적 102㎡초과', '전용면적 85㎡초과 102㎡이하', '전용면적 60㎡이하', '전용면적 60㎡초과 85㎡이하', '전용면적 60㎡초과 85㎡이하', '전용면적 85㎡초과 102㎡이하', '전용면적 102㎡초과', '전용면적 85㎡초과 102㎡이하', '전용면적 85㎡초과 102㎡이하', '전용면적 102㎡초과', '전용면적 102㎡초과', '전용면적 60㎡초과 85㎡이하', '전용면적 60㎡초과 85㎡이하', '전용면적 60㎡초과 85㎡이하', '전용면적 60㎡이하', '전용면적 60㎡초과 85㎡이하', '전용면적 60㎡초과 85㎡이하', '전용면적 60㎡초과 85㎡이하', '전용면적 60㎡이하', '전용면적 60㎡초과 85㎡이하', '전용면적 60㎡이하', '전용면적 60㎡초과 85㎡이하', '전용면적 102㎡초과', '전용면적 60㎡초과 85㎡이하', '전용면적 102㎡초과', '전용면적 102㎡초과', '전용면적 60㎡이하', '전용면적 60㎡이하', '전용면적 60㎡초과 85㎡이하']


[<p class="arrow"></p>, <p class="arrow"></p>, <p class="arrow"></p>, <p class="tag_blue">분양중</p>, <p>도·생</p>, <p>22,900 ~ 24,900만원</p>, <p>15 세대</p>, <p>2017.03 분양</p>, <p>2017.03 입주</p>, <p class="tag_blue">분양중</p>, <p>기타</p>, <p>22,000 ~ 28,800만원</p>, <p>11 세대</p>, <p>2017.03 분양</p>, <p>2017.03 입주</p>, <p class="tag_blue">분양중</p>, <p>기타</p>, <p>27,000 ~ 28,500만원</p>, <p>10 세대</p>, <p>2017.03 분양</p>, <p>2017.02 입주</p>, <p class="tag_blue">분양중</p>, <p>기타</p>, <p>24,900 ~ 25,500만원</p>, <p>10 세대</p>, <p>2017.03 분양</p>, <p>2017.03 입주</p>, <p class="tag_blue">분양중</p>, <p>도·생</p>, <p>14,900 ~ 19,900만원</p>, <p>30 세대</p>, <p>2017.03 분양</p>, <p>2017.03 입주</p>, <p class="tag_blue">분양중</p>, <p>기타</p>, <p>26,900만원</p>, <p>12 세대</p>, <p>2017.03 분양</p>, <p>2017.04 입주</p>, <p class="tag_blue">분양중</p>, <p>도·생</p>, <p>21,000만원</p>, <p>20 세대</p>, <p>2017.03 분양</p>, <p>2017.03 입주</p>, <p class="tag_blue">분양중</p>, <p>도·생</p>, <p>23,300 ~ 31,800만원</p>, <p>22 세대</p>, <p>2017.03 분양</p>, <p>2017.03 입주</p>, <p class="tag_blue">분양중</p>, <p>아파트</p>, <p>41,600 ~ 62,200만원</p>, <p>1,028 세대</p>, <p>2017.03 분양</p>, <p>2019.09 입주</p>, <p class="tag_blue">분양중</p>, <p>기타</p>, <p>21,900 ~ 23,900만원</p>, <p>15 세대</p>, <p>2017.03 분양</p>, <p>2017.02 입주</p>, <p class="tag_blue">분양중</p>, <p>아파트</p>, <p>42,000 ~ 62,000만원</p>, <p>691 세대</p>, <p>2017.03 분양</p>, <p>2020.10 입주</p>, <p class="tag_blue">분양중</p>, <p>아파트</p>, <p>39,700 ~ 57,210만원</p>, <p>1,305 세대</p>, <p>2017.03 분양</p>, <p>2019.08 입주</p>, <p class="tag_blue">분양중</p>, <p>기타</p>, <p>23,800 ~ 27,800만원</p>, <p>8 세대</p>, <p>2017.02 분양</p>, <p>2017.03 입주</p>, <p class="tag_blue">분양중</p>, <p>기타</p>, <p>27,900만원</p>, <p>10 세대</p>, <p>2017.02 분양</p>, <p>2017.02 입주</p>, <p class="tag_blue">분양중</p>, <p>도·생</p>, <p>22,700 ~ 26,900만원</p>, <p>14 세대</p>, <p>2017.02 분양</p>, <p>2017.02 입주</p>, <p>아파트</p>, <p>아파트</p>, <p>아파트</p>, <p>아파트</p>, <p>아파트</p>, <p>제호 [ 분양정보닷컴 ]</p>, <p>고객센터</p>]


22,900 ~ 24,900만원
22,000 ~ 28,800만원
27,000 ~ 28,500만원
24,900 ~ 25,500만원
14,900 ~ 19,900만원
26,900만원
21,000만원
23,300 ~ 31,800만원
41,600 ~ 62,200만원
21,900 ~ 23,900만원
42,000 ~ 62,000만원
39,700 ~ 57,210만원
23,800 ~ 27,800만원
27,900만원
22,700 ~ 26,900만원


[1947700, 171960, 1385000, 85120, 1289000, 890000, 345000, 2277000, 350500, 240000, 316200, 661000, 826400, 350290, 681580, 828000, 356800, 289800, 497100, 399000, 1058280, 2500000, 731100, 648500, 723300, 149900, 585200, 552800, 729000, 197000, 739000, 299000, 596610, 1043000, 2178000, 545000, 546500, 647400, 2091500, 547700, 655600, 1012000, 685480, 685480, 899000, 6254100, 110000, 858000, 638000, 282000, 205000, 770000, 535500, 275000, 639950, 700000, 939000, 1991000, 576000, 713000, 662000, 347000, 576000, 165000, 332000, 1001000, 415000, 376000, 318000, 1095000, 217570, 4390000, 497000, 399000, 2073800, 315000, 370000, 362000, 359000, 364000, 698000, 274000, 339000, 2135070, 1991500, 349000, 363000, 352000, '22,900 ~ 24,900만원', '22,000 ~ 28,800만원', '27,000 ~ 28,500만원', '24,900 ~ 25,500만원', '14,900 ~ 19,900만원', '26,900만원', '21,000만원', '23,300 ~ 31,800만원', '41,600 ~ 62,200만원', '21,900 ~ 23,900만원', '42,000 ~ 62,000만원', '39,700 ~ 57,210만원', '23,800 ~ 27,800만원', '27,900만원', '22,700 ~ 26,900만원']


[1947700, 171960, 1385000, 85120, 1289000, 890000, 345000, 2277000, 350500, 240000, 316200, 661000, 826400, 350290, 681580, 828000, 356800, 289800, 497100, 399000, 1058280, 2500000, 731100, 648500, 723300, 149900, 585200, 552800, 729000, 197000, 739000, 299000, 596610, 1043000, 2178000, 545000, 546500, 647400, 2091500, 547700, 655600, 1012000, 685480, 685480, 899000, 6254100, 110000, 858000, 638000, 282000, 205000, 770000, 535500, 275000, 639950, 700000, 939000, 1991000, 576000, 713000, 662000, 347000, 576000, 165000, 332000, 1001000, 415000, 376000, 318000, 1095000, 217570, 4390000, 497000, 399000, 2073800, 315000, 370000, 362000, 359000, 364000, 698000, 274000, 339000, 2135070, 1991500, 349000, 363000, 352000, 249000, 288000, 285000, 255000, 199000, 269000, 210000, 318000, 622000, 239000, 620000, 572100, 278000, 279000, 269000]
[19095, 2866, 13578, 1001, 12637, 8725, 5750, 22323, 5841, 4000, 5270, 6480, 8101, 5838, 6682, 8117, 5946, 4830, 4873, 4694, 10375, 29411, 7167, 6357, 7091, 2498, 5737, 5419, 7147, 3283, 7245, 4983, 9943, 10225, 21352, 5343, 5357, 6347, 20504, 5369, 7712, 9921, 6720, 6720, 8813, 61314, 1833, 8411, 6254, 4700, 3416, 7549, 5250, 4583, 6274, 11666, 9205, 19519, 5647, 6990, 7788, 4082, 5647, 2750, 5533, 9813, 4882, 6266, 3741, 10735, 3626, 43039, 8283, 3911, 20331, 3705, 6166, 4258, 4223, 4282, 6843, 3223, 3988, 20932, 19524, 4105, 4270, 4141, 249000, 288000, 285000, 255000, 199000, 269000, 210000, 318000, 622000, 239000, 620000, 572100, 278000, 279000, 269000]
[<p class="arrow"></p>, <p class="arrow"></p>, <p class="arrow"></p>, <p class="tag_blue">분양중</p>, <p>도·생</p>, <p>22,900 ~ 24,900만원</p>, <p>15 세대</p>, <p>2017.03 분양</p>, <p>2017.03 입주</p>, <p class="tag_blue">분양중</p>, <p>기타</p>, <p>22,000 ~ 28,800만원</p>, <p>11 세대</p>, <p>2017.03 분양</p>, <p>2017.03 입주</p>, <p class="tag_blue">분양중</p>, <p>기타</p>, <p>27,000 ~ 28,500만원</p>, <p>10 세대</p>, <p>2017.03 분양</p>, <p>2017.02 입주</p>, <p class="tag_blue">분양중</p>, <p>기타</p>, <p>24,900 ~ 25,500만원</p>, <p>10 세대</p>, <p>2017.03 분양</p>, <p>2017.03 입주</p>, <p class="tag_blue">분양중</p>, <p>도·생</p>, <p>14,900 ~ 19,900만원</p>, <p>30 세대</p>, <p>2017.03 분양</p>, <p>2017.03 입주</p>, <p class="tag_blue">분양중</p>, <p>기타</p>, <p>26,900만원</p>, <p>12 세대</p>, <p>2017.03 분양</p>, <p>2017.04 입주</p>, <p class="tag_blue">분양중</p>, <p>도·생</p>, <p>21,000만원</p>, <p>20 세대</p>, <p>2017.03 분양</p>, <p>2017.03 입주</p>, <p class="tag_blue">분양중</p>, <p>도·생</p>, <p>23,300 ~ 31,800만원</p>, <p>22 세대</p>, <p>2017.03 분양</p>, <p>2017.03 입주</p>, <p class="tag_blue">분양중</p>, <p>아파트</p>, <p>41,600 ~ 62,200만원</p>, <p>1,028 세대</p>, <p>2017.03 분양</p>, <p>2019.09 입주</p>, <p class="tag_blue">분양중</p>, <p>기타</p>, <p>21,900 ~ 23,900만원</p>, <p>15 세대</p>, <p>2017.03 분양</p>, <p>2017.02 입주</p>, <p class="tag_blue">분양중</p>, <p>아파트</p>, <p>42,000 ~ 62,000만원</p>, <p>691 세대</p>, <p>2017.03 분양</p>, <p>2020.10 입주</p>, <p class="tag_blue">분양중</p>, <p>아파트</p>, <p>39,700 ~ 57,210만원</p>, <p>1,305 세대</p>, <p>2017.03 분양</p>, <p>2019.08 입주</p>, <p class="tag_blue">분양중</p>, <p>기타</p>, <p>23,800 ~ 27,800만원</p>, <p>8 세대</p>, <p>2017.02 분양</p>, <p>2017.03 입주</p>, <p class="tag_blue">분양중</p>, <p>기타</p>, <p>27,900만원</p>, <p>10 세대</p>, <p>2017.02 분양</p>, <p>2017.02 입주</p>, <p class="tag_blue">분양중</p>, <p>도·생</p>, <p>22,700 ~ 26,900만원</p>, <p>14 세대</p>, <p>2017.02 분양</p>, <p>2017.02 입주</p>, <p>아파트</p>, <p>아파트</p>, <p>아파트</p>, <p>아파트</p>, <p>아파트</p>, <p>제호 [ 분양정보닷컴 ]</p>, <p>고객센터</p>]


2017.03 분양
2017.03 분양
2017.03 분양
2017.03 분양
2017.03 분양
2017.03 분양
2017.03 분양
2017.03 분양
2017.03 분양
2017.03 분양
2017.03 분양
2017.03 분양
2017.02 분양
2017.02 분양
2017.02 분양


['2019', '2019', '2019', '2019', '2019', '2019', '2018', '2018', '2018', '2018', '2018', '2018', '2018', '2018', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017.04 분양', '2017.04 분양', '2017.04 분양', '2017.04 분양', '2017.04 분양', '2017.04 분양', '2017.04 분양', '2017.04 분양', '2017.04 분양', '2017.04 분양', '2017.04 분양', '2017.03 분양', '2017.03 분양', '2017.03 분양', '2017.03 분양', '2017.03 분양', '2017.03 분양', '2017.03 분양', '2017.03 분양', '2017.03 분양', '2017.03 분양', '2017.03 분양', '2017.03 분양', '2017.03 분양', '2017.03 분양', '2017.03 분양', '2017.03 분양', '2017.02 분양', '2017.02 분양', '2017.02 분양']


['2019', '2019', '2019', '2019', '2019', '2019', '2018', '2018', '2018', '2018', '2018', '2018', '2018', '2018', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017.04 분양', '2017.04 분양', '2017.04 분양', '2017.04 분양', '2017.04 분양', '2017.04 분양', '2017.04 분양', '2017.04 분양', '2017.04 분양', '2017.04 분양', '2017.04 분양', '2017.03 분양', '2017.03 분양', '2017.03 분양', '2017.03 분양', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017']

    지역명               규모구분     분양가격  평당분양가격          연도
0    서울        전용면적 102㎡초과  1947700   19095        2019
1    서울         전용면적 60㎡이하   171960    2866        2019
2    서울        전용면적 102㎡초과  1385000   13578        2019
3    서울   전용면적 60㎡초과 85㎡이하    85120    1001        2019
4    서울  전용면적 85㎡초과 102㎡이하  1289000   12637        2019
5    서울        전용면적 102㎡초과   890000    8725        2019
6    서울         전용면적 60㎡이하   345000    5750        2018
7    서울        전용면적 102㎡초과  2277000   22323        2018
8    서울         전용면적 60㎡이하   350500    5841        2018
9    서울         전용면적 60㎡이하   240000    4000        2018
10   서울         전용면적 60㎡이하   316200    5270        2018
11   서울        전용면적 102㎡초과   661000    6480        2018
12   서울        전용면적 102㎡초과   826400    8101        2018
13   서울         전용면적 60㎡이하   350290    5838        2018
14   서울        전용면적 102㎡초과   681580    6682        2017
15   서울        전용면적 102㎡초과   828000    8117        2017
16   서울         전용면적 60㎡이하   356800    5946        2017
17   서울         전용면적 60㎡이하   289800    4830        2017
18   서울        전용면적 102㎡초과   497100    4873        2017
19   서울   전용면적 60㎡초과 85㎡이하   399000    4694        2017
20   서울        전용면적 102㎡초과  1058280   10375        2017
21   서울   전용면적 60㎡초과 85㎡이하  2500000   29411        2017
22   서울        전용면적 102㎡초과   731100    7167        2017
23   서울        전용면적 102㎡초과   648500    6357        2017
24   서울        전용면적 102㎡초과   723300    7091        2017
25   서울         전용면적 60㎡이하   149900    2498        2017
26   서울        전용면적 102㎡초과   585200    5737        2017
27   서울        전용면적 102㎡초과   552800    5419        2017
28   서울        전용면적 102㎡초과   729000    7147        2017
29   서울         전용면적 60㎡이하   197000    3283        2017
..   ..                ...      ...     ...         ...
73   서울        전용면적 102㎡초과   399000    3911  2017.04 분양
74   서울        전용면적 102㎡초과  2073800   20331  2017.04 분양
75   서울  전용면적 85㎡초과 102㎡이하   315000    3705  2017.04 분양
76   서울         전용면적 60㎡이하   370000    6166  2017.04 분양
77   서울   전용면적 60㎡초과 85㎡이하   362000    4258  2017.04 분양
78   서울   전용면적 60㎡초과 85㎡이하   359000    4223  2017.04 분양
79   서울  전용면적 85㎡초과 102㎡이하   364000    4282  2017.04 분양
80   서울        전용면적 102㎡초과   698000    6843  2017.04 분양
81   서울  전용면적 85㎡초과 102㎡이하   274000    3223  2017.04 분양
82   서울  전용면적 85㎡초과 102㎡이하   339000    3988  2017.04 분양
83   서울        전용면적 102㎡초과  2135070   20932  2017.04 분양
84   서울        전용면적 102㎡초과  1991500   19524  2017.03 분양
85   서울   전용면적 60㎡초과 85㎡이하   349000    4105  2017.03 분양
86   서울   전용면적 60㎡초과 85㎡이하   363000    4270  2017.03 분양
87   서울   전용면적 60㎡초과 85㎡이하   352000    4141  2017.03 분양
88   서울         전용면적 60㎡이하   249000    4150        2017
89   서울   전용면적 60㎡초과 85㎡이하   288000    3388        2017
90   서울   전용면적 60㎡초과 85㎡이하   285000    3352        2017
91   서울   전용면적 60㎡초과 85㎡이하   255000    3000        2017
92   서울         전용면적 60㎡이하   199000    3316        2017
93   서울   전용면적 60㎡초과 85㎡이하   269000    3164        2017
94   서울         전용면적 60㎡이하   210000    3500        2017
95   서울   전용면적 60㎡초과 85㎡이하   318000    3741        2017
96   서울        전용면적 102㎡초과   622000    6098        2017
97   서울   전용면적 60㎡초과 85㎡이하   239000    2811        2017
98   서울        전용면적 102㎡초과   620000    6078        2017
99   서울        전용면적 102㎡초과   572100    5608        2017
100  서울         전용면적 60㎡이하   278000    4633        2017
101  서울         전용면적 60㎡이하   279000    4650        2017
102  서울   전용면적 60㎡초과 85㎡이하   269000    3164        2017

[103 rows x 5 columns]

In [50]:
#[8 page]
def get_html(url) :
    html = ""
    resp = requests.get(url)
    if resp.status_code == 200 :
        html = resp.text
    return html
html = get_html('http://www.boonyang24.com/?sub=boonyang_info/info_list&do1=&si1=&boonryu01=&boonryu02=&page=8&keyword=&tp=&cate=&area_code=&work_year=&hyun_cate=')
soup = BeautifulSoup(html, 'html.parser')
boonyang = soup.find("div",{"class":"list_type_boonyang"})
#----------------------------------------------------------------------

#지역에 대한 리스트
Citycell = {}

w_city7 = soup.find_all('td', {'class':'subject'})
#다 서울이기 때문에 모든 리스트의 요소를 '서울'로 간단하게 바꿔줌. 

for i in range(0, 15):   #0~14
    w_city7[i]
    print(w_city7[i].text)
print('\n')

for i in range(0, 15):
    w_city7[i] = "서울"
for i in range(0, 15):
    w_city_l.append(w_city7[i])
    
print(w_city_l)
print('\n')

Citycell['지역명'] = w_city_l
sd = pd.DataFrame(Citycell)
sd = sd[['지역명']]

#----------------------------------------------------------------------
#----------------------------------------------------------------------
#규모에 대한 내용.
# "전용면적 60㎡이하" = 60 ,   "전용면적 60㎡초과 85㎡이하" = 85
# "전용면적 85㎡초과 102㎡이하" = 85,  "전용면적 102㎡초과" =102
w_size7 = soup.find_all('b')
for i in range(0, 13):  #28개
    del w_size7[i]
w_size7[0] = "전용면적 60㎡초과 85㎡이하"
w_size7[1] = "전용면적 60㎡초과 85㎡이하"
w_size7[2] = "전용면적 60㎡이하"
w_size7[3] = "전용면적 60㎡초과 85㎡이하"
w_size7[4] = "전용면적 60㎡이하"
w_size7[5] = "전용면적 60㎡초과 85㎡이하"
w_size7[6] = "전용면적 102㎡초과"
w_size7[7] = "전용면적 60㎡초과 85㎡이하"
w_size7[8] = "전용면적 60㎡이하"
w_size7[9] = "전용면적 60㎡이하"
w_size7[10] = "전용면적 60㎡초과 85㎡이하"
w_size7[11] = "전용면적 60㎡이하"
w_size7[12] = "전용면적 60㎡이하"
w_size7[13] = "전용면적 60㎡이하"
w_size7[14] = "전용면적 60㎡이하"
print(w_size7)

for i in range(0, 15):
    w_size_l.append(w_size7[i])
print(w_size_l)

Citycell['지역명'] = w_city_l
Citycell['규모구분'] = w_size_l
sd = pd.DataFrame(Citycell)
sd = sd[['지역명', '규모구분']]

#----------------------------------------------------------------------
print('\n')
w_price7 = soup.find_all('p')
print(w_price7)               #6번째 주기로 가격정보가 나오는걸 알 수 있다.
                            #'미정'처리된 두 지역은 빼고 생각하였다.
print('\n')
for i in range(1,16):
    print(w_price7[6*i-1].text)   
    w_price_l.extend(w_price7[6*i-1])   #등차수열 이용.
print('\n')
print(w_price_l)
    
Citycell['지역명'] = w_city_l
Citycell['규모구분'] = w_size_l
Citycell['분양가격'] = w_price_l
sd = pd.DataFrame(Citycell)
sd = sd[['지역명', '규모구분','분양가격']]

#----------------------------------------------------------------------
#크롤링한 사이트는 단위가 '만 원'이다.
#본래 데이터분석을 한 자료의 단위는 '천 원'이므로 끝에 0을 더 붙여서 할당하였다.
w_price_l[103] = 284000
w_price_l[104] = 358000
w_price_l[105] = 257000
w_price_l[106] = 290000
w_price_l[107] = 215000
w_price_l[108] = 510000
w_price_l[109] = 298000
w_price_l[110] = 215000
w_price_l[111] = 239000
w_price_l[112] = 155000
w_price_l[113] = 335000
w_price_l[114] = 195000
w_price_l[115] = 290000
w_price_l[116] = 192000
w_price_l[117] = 235000

print('\n')
print(w_price_l)
#pandas 처리
sd = pd.DataFrame(Citycell)
sd = sd[['지역명', '규모구분','분양가격']]

#----------------------------------------------------------------------
#평당분양가격
sd['분양가격'] = pd.to_numeric(w_price_l, errors = 'coerce')

for i in range(103,118):
    w_square.append(w_price_l[i])
print(w_square)
w_square[103] = int(284000/85)
w_square[104] = int(358000/85)
w_square[105] = int(257000/60)
w_square[106] = int(290000/85)
w_square[107] = int(215000/60)
w_square[108] = int(510000/85)
w_square[109] = int(298000/102)
w_square[110] = int(215000/85)
w_square[111] = int(239000/60)
w_square[112] = int(155000/60)
w_square[113] = int(335000/85)
w_square[114] = int(195000/60)
w_square[115] = int(290000/60)
w_square[116] = int(192000/60)
w_square[117] = int(235000/60)

Citycell['평당분양가격'] = w_square
sd = pd.DataFrame(Citycell)
sd = sd[['지역명', '규모구분','분양가격','평당분양가격']]

#----------------------------------------------------------------------

#연도에 대한 리스트 필요.
w_year7 = soup.find_all('p')
print(w_year7)
print('\n')
#7, 13, 19, 25 a+(n-1)d
#7+(i-1)*6        // 등차수열 이용.
for i in range(1,16):
    print(w_year7[7+(i-1)*6].text)    
    w_year_l.extend(w_year7[7+(i-1)*6])
    
print('\n')
print(w_year_l)

for i in range(103,118):
    w_year_l[i] = '2017'
print('\n')
print(w_year_l)

#pandas 처리
Citycell['지역명'] = w_city_l
Citycell['규모구분'] = w_size_l
Citycell['가격'] = w_price_l
Citycell['연도'] = w_year_l

sd = pd.DataFrame(Citycell)
sd = sd[['지역명', '규모구분','분양가격','평당분양가격', '연도']]
sd

다인홈타운 서울 양천구 신월동 18-11
미래하이빌 서울 동작구 사당동 1051-28
목동로데오빌 서울 양천구 신정동 890-6
초원그린빌 서울 은평구 구산동 368-53
라임하우스 서울 은평구 녹번동 29-35
삼성프라임 서울 은평구 역촌동 22-48
상진라인빌 서울 강동구 천호동 330-4
평화아트빌 서울 강서구 등촌동 574-3
티에스빌 서울 금천구 시흥동 822-54
예담리치빌 서울 양천구 신월동 110-11
첼라넥스빌 서울 은평구 응암동 596-13
아산피렌체 서울 강북구 수유동 270-62
이든하우스 서울 송파구 가락동 12
나린하임 서울 강서구 화곡동 976-4
보노하우스8차 서울 양천구 신정동 920-25


['서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울', '서울']


['전용면적 60㎡초과 85㎡이하', '전용면적 60㎡초과 85㎡이하', '전용면적 60㎡이하', '전용면적 60㎡초과 85㎡이하', '전용면적 60㎡이하', '전용면적 60㎡초과 85㎡이하', '전용면적 102㎡초과', '전용면적 60㎡초과 85㎡이하', '전용면적 60㎡이하', '전용면적 60㎡이하', '전용면적 60㎡초과 85㎡이하', '전용면적 60㎡이하', '전용면적 60㎡이하', '전용면적 60㎡이하', '전용면적 60㎡이하']
['전용면적 102㎡초과', '전용면적 60㎡이하', '전용면적 102㎡초과', '전용면적 60㎡초과 85㎡이하', '전용면적 85㎡초과 102㎡이하', '전용면적 102㎡초과', '전용면적 60㎡이하', '전용면적 102㎡초과', '전용면적 60㎡이하', '전용면적 60㎡이하', '전용면적 60㎡이하', '전용면적 102㎡초과', '전용면적 102㎡초과', '전용면적 60㎡이하', '전용면적 102㎡초과', '전용면적 102㎡초과', '전용면적 60㎡이하', '전용면적 60㎡이하', '전용면적 102㎡초과', '전용면적 60㎡초과 85㎡이하', '전용면적 102㎡초과', '전용면적 60㎡초과 85㎡이하', '전용면적 102㎡초과', '전용면적 102㎡초과', '전용면적 102㎡초과', '전용면적 60㎡이하', '전용면적 102㎡초과', '전용면적 102㎡초과', '전용면적 102㎡초과', '전용면적 60㎡이하', '전용면적 102㎡초과', '전용면적 60㎡이하', '전용면적 60㎡초과 85㎡이하', '전용면적 102㎡초과', '전용면적 102㎡초과', '전용면적 102㎡초과', '전용면적 102㎡초과', '전용면적 102㎡초과', '전용면적 102㎡초과', '전용면적 102㎡초과', '전용면적 85㎡초과 102㎡이하', '전용면적 102㎡초과', '전용면적 102㎡초과', '전용면적 102㎡초과', '전용면적 102㎡초과', '전용면적 102㎡초과', '전용면적 60㎡이하', '전용면적 102㎡초과', '전용면적 102㎡초과', '전용면적 60㎡이하', '전용면적 60㎡이하', '전용면적 102㎡초과', '전용면적 102㎡초과', '전용면적 60㎡이하', '전용면적 102㎡초과', '전용면적 60㎡이하', '전용면적 102㎡초과', '전용면적 102㎡초과', '전용면적 102㎡초과', '전용면적 102㎡초과', '전용면적 60㎡초과 85㎡이하', '전용면적 60㎡초과 85㎡이하', '전용면적 102㎡초과', '전용면적 60㎡이하', '전용면적 60㎡이하', '전용면적 102㎡초과', '전용면적 60㎡초과 85㎡이하', '전용면적 60㎡이하', '전용면적 60㎡초과 85㎡이하', '전용면적 102㎡초과', '전용면적 60㎡이하', '전용면적 102㎡초과', '전용면적 60㎡이하', '전용면적 102㎡초과', '전용면적 102㎡초과', '전용면적 85㎡초과 102㎡이하', '전용면적 60㎡이하', '전용면적 60㎡초과 85㎡이하', '전용면적 60㎡초과 85㎡이하', '전용면적 85㎡초과 102㎡이하', '전용면적 102㎡초과', '전용면적 85㎡초과 102㎡이하', '전용면적 85㎡초과 102㎡이하', '전용면적 102㎡초과', '전용면적 102㎡초과', '전용면적 60㎡초과 85㎡이하', '전용면적 60㎡초과 85㎡이하', '전용면적 60㎡초과 85㎡이하', '전용면적 60㎡이하', '전용면적 60㎡초과 85㎡이하', '전용면적 60㎡초과 85㎡이하', '전용면적 60㎡초과 85㎡이하', '전용면적 60㎡이하', '전용면적 60㎡초과 85㎡이하', '전용면적 60㎡이하', '전용면적 60㎡초과 85㎡이하', '전용면적 102㎡초과', '전용면적 60㎡초과 85㎡이하', '전용면적 102㎡초과', '전용면적 102㎡초과', '전용면적 60㎡이하', '전용면적 60㎡이하', '전용면적 60㎡초과 85㎡이하', '전용면적 60㎡초과 85㎡이하', '전용면적 60㎡초과 85㎡이하', '전용면적 60㎡이하', '전용면적 60㎡초과 85㎡이하', '전용면적 60㎡이하', '전용면적 60㎡초과 85㎡이하', '전용면적 102㎡초과', '전용면적 60㎡초과 85㎡이하', '전용면적 60㎡이하', '전용면적 60㎡이하', '전용면적 60㎡초과 85㎡이하', '전용면적 60㎡이하', '전용면적 60㎡이하', '전용면적 60㎡이하', '전용면적 60㎡이하']


[<p class="arrow"></p>, <p class="arrow"></p>, <p class="arrow"></p>, <p class="tag_blue">분양중</p>, <p>기타</p>, <p>27,500 ~ 28,400만원</p>, <p>18 세대</p>, <p>2017.02 분양</p>, <p>2017.02 입주</p>, <p class="tag_blue">분양중</p>, <p>도·생</p>, <p>35,800만원</p>, <p>8 세대</p>, <p>2017.02 분양</p>, <p>2017.02 입주</p>, <p class="tag_blue">분양중</p>, <p>도·생</p>, <p>21,200 ~ 25,700만원</p>, <p>12 세대</p>, <p>2017.02 분양</p>, <p>2017.03 입주</p>, <p class="tag_blue">분양중</p>, <p>도·생</p>, <p>20,000 ~ 29,000만원</p>, <p>8 세대</p>, <p>2017.02 분양</p>, <p>2017.02 입주</p>, <p class="tag_blue">분양중</p>, <p>기타</p>, <p>21,500만원</p>, <p>20 세대</p>, <p>2017.02 분양</p>, <p>2017.02 입주</p>, <p class="tag_blue">분양중</p>, <p>기타</p>, <p>23,800 ~ 51,000만원</p>, <p>9 세대</p>, <p>2017.02 분양</p>, <p>2017.02 입주</p>, <p class="tag_blue">분양중</p>, <p>도·생</p>, <p>22,900 ~ 29,800만원</p>, <p>29 세대</p>, <p>2017.02 분양</p>, <p>2017.02 입주</p>, <p class="tag_blue">분양중</p>, <p>도·생</p>, <p>15,900 ~ 21,500만원</p>, <p>20 세대</p>, <p>2017.02 분양</p>, <p>2017.02 입주</p>, <p class="tag_blue">분양중</p>, <p>기타</p>, <p>19,700 ~ 23,900만원</p>, <p>15 세대</p>, <p>2017.02 분양</p>, <p>2017.02 입주</p>, <p class="tag_blue">분양중</p>, <p>기타</p>, <p>16,000 ~ 15,500만원</p>, <p>15 세대</p>, <p>2017.02 분양</p>, <p>2017.02 입주</p>, <p class="tag_blue">분양중</p>, <p>도·생</p>, <p>33,500만원</p>, <p>10 세대</p>, <p>2017.02 분양</p>, <p>2017.02 입주</p>, <p class="tag_blue">분양중</p>, <p>기타</p>, <p>17,500 ~ 19,500만원</p>, <p>10 세대</p>, <p>2017.02 분양</p>, <p>2017.02 입주</p>, <p class="tag_blue">분양중</p>, <p>도·생</p>, <p>28,500 ~ 29,000만원</p>, <p>29 세대</p>, <p>2017.02 분양</p>, <p>2017.02 입주</p>, <p class="tag_blue">분양중</p>, <p>기타</p>, <p>17,200 ~ 19,200만원</p>, <p>38 세대</p>, <p>2017.02 분양</p>, <p>2017.02 입주</p>, <p class="tag_blue">분양중</p>, <p>기타</p>, <p>19,800 ~ 23,500만원</p>, <p>13 세대</p>, <p>2017.02 분양</p>, <p>2017.02 입주</p>, <p>아파트</p>, <p>아파트</p>, <p>아파트</p>, <p>아파트</p>, <p>아파트</p>, <p>제호 [ 분양정보닷컴 ]</p>, <p>고객센터</p>]


27,500 ~ 28,400만원
35,800만원
21,200 ~ 25,700만원
20,000 ~ 29,000만원
21,500만원
23,800 ~ 51,000만원
22,900 ~ 29,800만원
15,900 ~ 21,500만원
19,700 ~ 23,900만원
16,000 ~ 15,500만원
33,500만원
17,500 ~ 19,500만원
28,500 ~ 29,000만원
17,200 ~ 19,200만원
19,800 ~ 23,500만원


[1947700, 171960, 1385000, 85120, 1289000, 890000, 345000, 2277000, 350500, 240000, 316200, 661000, 826400, 350290, 681580, 828000, 356800, 289800, 497100, 399000, 1058280, 2500000, 731100, 648500, 723300, 149900, 585200, 552800, 729000, 197000, 739000, 299000, 596610, 1043000, 2178000, 545000, 546500, 647400, 2091500, 547700, 655600, 1012000, 685480, 685480, 899000, 6254100, 110000, 858000, 638000, 282000, 205000, 770000, 535500, 275000, 639950, 700000, 939000, 1991000, 576000, 713000, 662000, 347000, 576000, 165000, 332000, 1001000, 415000, 376000, 318000, 1095000, 217570, 4390000, 497000, 399000, 2073800, 315000, 370000, 362000, 359000, 364000, 698000, 274000, 339000, 2135070, 1991500, 349000, 363000, 352000, 249000, 288000, 285000, 255000, 199000, 269000, 210000, 318000, 622000, 239000, 620000, 572100, 278000, 279000, 269000, '27,500 ~ 28,400만원', '35,800만원', '21,200 ~ 25,700만원', '20,000 ~ 29,000만원', '21,500만원', '23,800 ~ 51,000만원', '22,900 ~ 29,800만원', '15,900 ~ 21,500만원', '19,700 ~ 23,900만원', '16,000 ~ 15,500만원', '33,500만원', '17,500 ~ 19,500만원', '28,500 ~ 29,000만원', '17,200 ~ 19,200만원', '19,800 ~ 23,500만원']


[1947700, 171960, 1385000, 85120, 1289000, 890000, 345000, 2277000, 350500, 240000, 316200, 661000, 826400, 350290, 681580, 828000, 356800, 289800, 497100, 399000, 1058280, 2500000, 731100, 648500, 723300, 149900, 585200, 552800, 729000, 197000, 739000, 299000, 596610, 1043000, 2178000, 545000, 546500, 647400, 2091500, 547700, 655600, 1012000, 685480, 685480, 899000, 6254100, 110000, 858000, 638000, 282000, 205000, 770000, 535500, 275000, 639950, 700000, 939000, 1991000, 576000, 713000, 662000, 347000, 576000, 165000, 332000, 1001000, 415000, 376000, 318000, 1095000, 217570, 4390000, 497000, 399000, 2073800, 315000, 370000, 362000, 359000, 364000, 698000, 274000, 339000, 2135070, 1991500, 349000, 363000, 352000, 249000, 288000, 285000, 255000, 199000, 269000, 210000, 318000, 622000, 239000, 620000, 572100, 278000, 279000, 269000, 284000, 358000, 257000, 290000, 215000, 510000, 298000, 215000, 239000, 155000, 335000, 195000, 290000, 192000, 235000]
[19095, 2866, 13578, 1001, 12637, 8725, 5750, 22323, 5841, 4000, 5270, 6480, 8101, 5838, 6682, 8117, 5946, 4830, 4873, 4694, 10375, 29411, 7167, 6357, 7091, 2498, 5737, 5419, 7147, 3283, 7245, 4983, 9943, 10225, 21352, 5343, 5357, 6347, 20504, 5369, 7712, 9921, 6720, 6720, 8813, 61314, 1833, 8411, 6254, 4700, 3416, 7549, 5250, 4583, 6274, 11666, 9205, 19519, 5647, 6990, 7788, 4082, 5647, 2750, 5533, 9813, 4882, 6266, 3741, 10735, 3626, 43039, 8283, 3911, 20331, 3705, 6166, 4258, 4223, 4282, 6843, 3223, 3988, 20932, 19524, 4105, 4270, 4141, 4150, 3388, 3352, 3000, 3316, 3164, 3500, 3741, 6098, 2811, 6078, 5608, 4633, 4650, 3164, 284000, 358000, 257000, 290000, 215000, 510000, 298000, 215000, 239000, 155000, 335000, 195000, 290000, 192000, 235000]
[<p class="arrow"></p>, <p class="arrow"></p>, <p class="arrow"></p>, <p class="tag_blue">분양중</p>, <p>기타</p>, <p>27,500 ~ 28,400만원</p>, <p>18 세대</p>, <p>2017.02 분양</p>, <p>2017.02 입주</p>, <p class="tag_blue">분양중</p>, <p>도·생</p>, <p>35,800만원</p>, <p>8 세대</p>, <p>2017.02 분양</p>, <p>2017.02 입주</p>, <p class="tag_blue">분양중</p>, <p>도·생</p>, <p>21,200 ~ 25,700만원</p>, <p>12 세대</p>, <p>2017.02 분양</p>, <p>2017.03 입주</p>, <p class="tag_blue">분양중</p>, <p>도·생</p>, <p>20,000 ~ 29,000만원</p>, <p>8 세대</p>, <p>2017.02 분양</p>, <p>2017.02 입주</p>, <p class="tag_blue">분양중</p>, <p>기타</p>, <p>21,500만원</p>, <p>20 세대</p>, <p>2017.02 분양</p>, <p>2017.02 입주</p>, <p class="tag_blue">분양중</p>, <p>기타</p>, <p>23,800 ~ 51,000만원</p>, <p>9 세대</p>, <p>2017.02 분양</p>, <p>2017.02 입주</p>, <p class="tag_blue">분양중</p>, <p>도·생</p>, <p>22,900 ~ 29,800만원</p>, <p>29 세대</p>, <p>2017.02 분양</p>, <p>2017.02 입주</p>, <p class="tag_blue">분양중</p>, <p>도·생</p>, <p>15,900 ~ 21,500만원</p>, <p>20 세대</p>, <p>2017.02 분양</p>, <p>2017.02 입주</p>, <p class="tag_blue">분양중</p>, <p>기타</p>, <p>19,700 ~ 23,900만원</p>, <p>15 세대</p>, <p>2017.02 분양</p>, <p>2017.02 입주</p>, <p class="tag_blue">분양중</p>, <p>기타</p>, <p>16,000 ~ 15,500만원</p>, <p>15 세대</p>, <p>2017.02 분양</p>, <p>2017.02 입주</p>, <p class="tag_blue">분양중</p>, <p>도·생</p>, <p>33,500만원</p>, <p>10 세대</p>, <p>2017.02 분양</p>, <p>2017.02 입주</p>, <p class="tag_blue">분양중</p>, <p>기타</p>, <p>17,500 ~ 19,500만원</p>, <p>10 세대</p>, <p>2017.02 분양</p>, <p>2017.02 입주</p>, <p class="tag_blue">분양중</p>, <p>도·생</p>, <p>28,500 ~ 29,000만원</p>, <p>29 세대</p>, <p>2017.02 분양</p>, <p>2017.02 입주</p>, <p class="tag_blue">분양중</p>, <p>기타</p>, <p>17,200 ~ 19,200만원</p>, <p>38 세대</p>, <p>2017.02 분양</p>, <p>2017.02 입주</p>, <p class="tag_blue">분양중</p>, <p>기타</p>, <p>19,800 ~ 23,500만원</p>, <p>13 세대</p>, <p>2017.02 분양</p>, <p>2017.02 입주</p>, <p>아파트</p>, <p>아파트</p>, <p>아파트</p>, <p>아파트</p>, <p>아파트</p>, <p>제호 [ 분양정보닷컴 ]</p>, <p>고객센터</p>]


2017.02 분양
2017.02 분양
2017.02 분양
2017.02 분양
2017.02 분양
2017.02 분양
2017.02 분양
2017.02 분양
2017.02 분양
2017.02 분양
2017.02 분양
2017.02 분양
2017.02 분양
2017.02 분양
2017.02 분양


['2019', '2019', '2019', '2019', '2019', '2019', '2018', '2018', '2018', '2018', '2018', '2018', '2018', '2018', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017.04 분양', '2017.04 분양', '2017.04 분양', '2017.04 분양', '2017.04 분양', '2017.04 분양', '2017.04 분양', '2017.04 분양', '2017.04 분양', '2017.04 분양', '2017.04 분양', '2017.03 분양', '2017.03 분양', '2017.03 분양', '2017.03 분양', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017.02 분양', '2017.02 분양', '2017.02 분양', '2017.02 분양', '2017.02 분양', '2017.02 분양', '2017.02 분양', '2017.02 분양', '2017.02 분양', '2017.02 분양', '2017.02 분양', '2017.02 분양', '2017.02 분양', '2017.02 분양', '2017.02 분양']


['2019', '2019', '2019', '2019', '2019', '2019', '2018', '2018', '2018', '2018', '2018', '2018', '2018', '2018', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017.04 분양', '2017.04 분양', '2017.04 분양', '2017.04 분양', '2017.04 분양', '2017.04 분양', '2017.04 분양', '2017.04 분양', '2017.04 분양', '2017.04 분양', '2017.04 분양', '2017.03 분양', '2017.03 분양', '2017.03 분양', '2017.03 분양', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017']

    지역명               규모구분     분양가격  평당분양가격    연도
0    서울        전용면적 102㎡초과  1947700   19095  2019
1    서울         전용면적 60㎡이하   171960    2866  2019
2    서울        전용면적 102㎡초과  1385000   13578  2019
3    서울   전용면적 60㎡초과 85㎡이하    85120    1001  2019
4    서울  전용면적 85㎡초과 102㎡이하  1289000   12637  2019
5    서울        전용면적 102㎡초과   890000    8725  2019
6    서울         전용면적 60㎡이하   345000    5750  2018
7    서울        전용면적 102㎡초과  2277000   22323  2018
8    서울         전용면적 60㎡이하   350500    5841  2018
9    서울         전용면적 60㎡이하   240000    4000  2018
10   서울         전용면적 60㎡이하   316200    5270  2018
11   서울        전용면적 102㎡초과   661000    6480  2018
12   서울        전용면적 102㎡초과   826400    8101  2018
13   서울         전용면적 60㎡이하   350290    5838  2018
14   서울        전용면적 102㎡초과   681580    6682  2017
15   서울        전용면적 102㎡초과   828000    8117  2017
16   서울         전용면적 60㎡이하   356800    5946  2017
17   서울         전용면적 60㎡이하   289800    4830  2017
18   서울        전용면적 102㎡초과   497100    4873  2017
19   서울   전용면적 60㎡초과 85㎡이하   399000    4694  2017
20   서울        전용면적 102㎡초과  1058280   10375  2017
21   서울   전용면적 60㎡초과 85㎡이하  2500000   29411  2017
22   서울        전용면적 102㎡초과   731100    7167  2017
23   서울        전용면적 102㎡초과   648500    6357  2017
24   서울        전용면적 102㎡초과   723300    7091  2017
25   서울         전용면적 60㎡이하   149900    2498  2017
26   서울        전용면적 102㎡초과   585200    5737  2017
27   서울        전용면적 102㎡초과   552800    5419  2017
28   서울        전용면적 102㎡초과   729000    7147  2017
29   서울         전용면적 60㎡이하   197000    3283  2017
..   ..                ...      ...     ...   ...
88   서울         전용면적 60㎡이하   249000    4150  2017
89   서울   전용면적 60㎡초과 85㎡이하   288000    3388  2017
90   서울   전용면적 60㎡초과 85㎡이하   285000    3352  2017
91   서울   전용면적 60㎡초과 85㎡이하   255000    3000  2017
92   서울         전용면적 60㎡이하   199000    3316  2017
93   서울   전용면적 60㎡초과 85㎡이하   269000    3164  2017
94   서울         전용면적 60㎡이하   210000    3500  2017
95   서울   전용면적 60㎡초과 85㎡이하   318000    3741  2017
96   서울        전용면적 102㎡초과   622000    6098  2017
97   서울   전용면적 60㎡초과 85㎡이하   239000    2811  2017
98   서울        전용면적 102㎡초과   620000    6078  2017
99   서울        전용면적 102㎡초과   572100    5608  2017
100  서울         전용면적 60㎡이하   278000    4633  2017
101  서울         전용면적 60㎡이하   279000    4650  2017
102  서울   전용면적 60㎡초과 85㎡이하   269000    3164  2017
103  서울   전용면적 60㎡초과 85㎡이하   284000    3341  2017
104  서울   전용면적 60㎡초과 85㎡이하   358000    4211  2017
105  서울         전용면적 60㎡이하   257000    4283  2017
106  서울   전용면적 60㎡초과 85㎡이하   290000    3411  2017
107  서울         전용면적 60㎡이하   215000    3583  2017
108  서울   전용면적 60㎡초과 85㎡이하   510000    6000  2017
109  서울        전용면적 102㎡초과   298000    2921  2017
110  서울   전용면적 60㎡초과 85㎡이하   215000    2529  2017
111  서울         전용면적 60㎡이하   239000    3983  2017
112  서울         전용면적 60㎡이하   155000    2583  2017
113  서울   전용면적 60㎡초과 85㎡이하   335000    3941  2017
114  서울         전용면적 60㎡이하   195000    3250  2017
115  서울         전용면적 60㎡이하   290000    4833  2017
116  서울         전용면적 60㎡이하   192000    3200  2017
117  서울         전용면적 60㎡이하   235000    3916  2017

[118 rows x 5 columns]